openapi: 3.0.0
info:
  title: ca-mis-success-and-support-services-term-data-counsel-advise
  description: API for SVAMSTD administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SVAMSTD
  x-source-domain: Student
  x-source-title: MIS Success and Support Services Term Data (California)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/ca-mis-success-and-support-services-term-data-counsel-advise:
    get:
      tags:
        - ca-mis-success-and-support-services-term-data-counsel-advise
      summary: Return resources from SVAMSTD
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: svamstdTermCode
          in: query
          required: false
          schema:
            type: string
        - name: svamstdDicdCode
          in: query
          required: false
          schema:
            type: string
        - name: costCode
          in: query
          description: Counsel/Advise
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_COST_CODE
        - name: ssstCode
          in: query
          description: Status
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
        - name: svvcostNoncreditServiceInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        - name: serviceDate
          in: query
          description: Service Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        - name: ssgpCode
          in: query
          description: Group
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
        - name: spridenId
          in: query
          description: Provider User ID
          required: false
          schema:
            type: string
        - name: dataOrigin
          in: query
          description: Source
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        - name: origCode
          in: query
          description: Provider Origin
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
        - name: activityDate
          in: query
          description: Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        - name: userId
          in: query
          description: User ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SVRCNAD_USER_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                    el-advise-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - ca-mis-success-and-support-services-term-data-counsel-advise
      summary: Updates an existing resource in SVAMSTD
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                el-advise-1.0.0_put_request"
            example:
              serviceDate: 2022-09-09
              svamstdDicdCode: 90
              svamstdTermCode: 201410
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                    el-advise-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - ca-mis-success-and-support-services-term-data-counsel-advise
      summary: Creates a new resource in SVAMSTD
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                el-advise-1.0.0_post_request"
            example:
              costCode: CNS
              serviceDate: 2021-09-09
              svamstdDicdCode: 90
              svamstdTermCode: 201410
              id: A00030988
              origCode: ADMS
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                    el-advise-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/ca-mis-success-and-support-services-term-data-counsel-advise:
    post:
      tags:
        - ca-mis-success-and-support-services-term-data-counsel-advise QAPI
          (Query by POST)
      summary: Return resources from SVAMSTD
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                el-advise-1.0.0_get_request"
            example:
              svamstdDicdCode: 90
              svamstdTermCode: 201410
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ca-mis-success-and-support-services-term-data-couns\
                    el-advise-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        svamstdTermCode:
          type: string
        svamstdDicdCode:
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
        svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_get_request:
      required:
        - costCode
        - serviceDate
        - dataOrigin
        - origCode
      type: object
      properties:
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        svamstdDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamstdDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamstdDicdCode
          x-lineageLookupReferenceObject: gtvdicd
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        svamstdTermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : svamstdTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamstdTermCode
          x-lineageLookupReferenceObject: stvterm
        dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
      x-lineageReferenceObject: SVRCNAD
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_get_response:
      required:
        - costCode
        - dataOrigin
        - origCode
        - serviceDate
      type: object
      properties:
        seqNo:
          title: Sequence
          maxLength: 8
          type: number
          description: "Lineage reference object : SVRCNAD_SEQ_NO"
          x-lineageReferenceObject: SVRCNAD_SEQ_NO
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        ssstDesc:
          maxLength: 60
          type: string
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        origDesc:
          maxLength: 60
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        costDesc:
          maxLength: 60
          type: string
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        rwname:
          maxLength: 230
          type: string
        svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        ssgpDesc:
          maxLength: 60
          type: string
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
      x-lineageReferenceObject: svrcnad
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_post_request:
      required:
        - costCode
        - serviceDate
        - origCode
      type: object
      properties:
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        svamstdDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamstdDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamstdDicdCode
          x-lineageLookupReferenceObject: gtvdicd
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        name:
          maxLength: 230
          type: string
        svamstdTermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : svamstdTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamstdTermCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
      x-lineageReferenceObject: SVRCNAD
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_put_request:
      required:
        - criteria.costCode
        - criteria.serviceDate
        - criteria.dataOrigin
        - criteria.origCode
        - serviceDate
        - origCode
      type: object
      properties:
        criteria.spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        criteria.svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        criteria.serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        criteria.origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        criteria.activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        criteria.userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        svamstdDicdCode:
          title: District/College ID
          maxLength: 3
          type: string
          description: "Lineage reference object : svamstdDicdCode, Lookup lineage
            reference object : gtvdicd"
          x-lineageReferenceObject: svamstdDicdCode
          x-lineageLookupReferenceObject: gtvdicd
        criteria.ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
        criteria.costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        name:
          maxLength: 230
          type: string
        svamstdTermCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : svamstdTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: svamstdTermCode
          x-lineageLookupReferenceObject: stvterm
        criteria.ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
      x-lineageReferenceObject: SVRCNAD
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_put_response:
      required:
        - costCode
        - dataOrigin
        - origCode
        - serviceDate
      type: object
      properties:
        seqNo:
          title: Sequence
          maxLength: 8
          type: number
          description: "Lineage reference object : SVRCNAD_SEQ_NO"
          x-lineageReferenceObject: SVRCNAD_SEQ_NO
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        ssstDesc:
          maxLength: 60
          type: string
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        origDesc:
          maxLength: 60
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        costDesc:
          maxLength: 60
          type: string
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        rwname:
          maxLength: 230
          type: string
        svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        ssgpDesc:
          maxLength: 60
          type: string
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
      x-lineageReferenceObject: svrcnad
    ca-mis-success-and-support-services-term-data-counsel-advise-1.0.0_post_response:
      required:
        - costCode
        - dataOrigin
        - origCode
        - serviceDate
      type: object
      properties:
        seqNo:
          title: Sequence
          maxLength: 8
          type: number
          description: "Lineage reference object : SVRCNAD_SEQ_NO"
          x-lineageReferenceObject: SVRCNAD_SEQ_NO
        serviceDate:
          title: Service Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_SERVICE_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_SERVICE_DATE
        ssstDesc:
          maxLength: 60
          type: string
        userId:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_USER_ID"
          x-lineageReferenceObject: SVRCNAD_USER_ID
        origCode:
          title: Provider Origin
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_ORIG_CODE, Lookup lineage
            reference object : stvorig"
          x-lineageReferenceObject: SVRCNAD_ORIG_CODE
          x-lineageLookupReferenceObject: stvorig
        spridenId:
          title: Provider User ID
          maxLength: 9
          type: string
        costCode:
          title: Counsel/Advise
          maxLength: 6
          type: string
          description: "Lineage reference object : SVRCNAD_COST_CODE, Lookup lineage
            reference object : svvcost"
          x-lineageReferenceObject: SVRCNAD_COST_CODE
          x-lineageLookupReferenceObject: svvcost
        origDesc:
          maxLength: 60
          type: string
        activityDate:
          title: Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SVRCNAD_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SVRCNAD_ACTIVITY_DATE
        costDesc:
          maxLength: 60
          type: string
        ssgpCode:
          title: Group
          maxLength: 4
          type: string
          description: "Lineage reference object : SVRCNAD_SSGP_CODE, Lookup lineage
            reference object : stvssgp"
          x-lineageReferenceObject: SVRCNAD_SSGP_CODE
          x-lineageLookupReferenceObject: stvssgp
        rwname:
          maxLength: 230
          type: string
        svvcostNoncreditServiceInd:
          type: string
          description: "Lineage reference object : SVVCOST_NONCREDIT_SERVICE_IND"
          x-lineageReferenceObject: SVVCOST_NONCREDIT_SERVICE_IND
        dataOrigin:
          title: Source
          maxLength: 30
          type: string
          description: "Lineage reference object : SVRCNAD_DATA_ORIGIN"
          x-lineageReferenceObject: SVRCNAD_DATA_ORIGIN
        ssgpDesc:
          maxLength: 60
          type: string
        ssstCode:
          title: Status
          maxLength: 2
          type: string
          description: "Lineage reference object : SVRCNAD_SSST_CODE, Lookup lineage
            reference object : stvssst"
          x-lineageReferenceObject: SVRCNAD_SSST_CODE
          x-lineageLookupReferenceObject: stvssst
      x-lineageReferenceObject: svrcnad
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
