openapi: 3.0.0
info:
  title: student-adjustment-targets-waivers-substitutions-waivers
  description: API for SMASADJ administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: SMASADJ
  x-source-domain: Student
  x-source-title: "Student Targets, Waivers and Substitutions"
  x-source-system: banner
  x-api-type: bus-poc
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.ie
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
- url: "{server_url}"
  description: Custom server url
  variables:
    server_url:
      default: localhost
paths:
  /api/student-adjustment-targets-waivers-substitutions-waivers:
    get:
      tags:
      - student-adjustment-targets-waivers-substitutions-waivers
      summary: Return resources from SMASADJ
      parameters:
      - name: X-SDE-Expand
        in: header
        description: The comma separated value list of block names
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria as a single URL query parameter. Use this
          parameter or the individual parameters listed. Must be a JSON representation
          of the property searching for. This can be any of the properties listed
          on the URL or QAPI and must be a json representation that can be validated
          against the GET schema. Limit and Offset are the only supported additional
          parameters on the URL.
        required: false
        schema:
          type: string
      - name: id
        in: query
        required: false
        schema:
          type: string
      - name: keyblckTermCode
        in: query
        required: false
        schema:
          type: string
      - name: subjCode
        in: query
        description: Smrswav Subj Code
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
      - name: crseNumb
        in: query
        description: Smrswav Crse Numb
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
      - name: attrCode
        in: query
        description: Smrswav Attr Code
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_ATTR_CODE
      - name: area
        in: query
        description: Smrswav Area
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_AREA
      - name: group
        in: query
        description: Smrswav Group
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_GROUP
      - name: actnCode
        in: query
        description: Smrswav Actn Code
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_ACTN_CODE
      - name: credits
        in: query
        description: Smrswav Credits
        required: false
        schema:
          type: string
        x-lineageReferenceObject: SMRSWAV_CREDITS
      - name: program
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_get_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
    put:
      tags:
      - student-adjustment-targets-waivers-substitutions-waivers
      summary: Updates an existing resource in SMASADJ
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_put_request'
            example:
              criteria.program: 1-11A2SDL
              actnCode: TES
              keyblckTermCode: 201520
              criteria.subjCode: '0001'
              id: A00076810
              program: 1-11BRZHT
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_put_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
    post:
      tags:
      - student-adjustment-targets-waivers-substitutions-waivers
      summary: Creates a new resource in SMASADJ
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_post_request'
            example:
              actnCode: TEN
              smrswavCrseNumb: '0002'
              smrswavSubjCode: '0002'
              keyblckTermCode: 201520
              id: A00076810
              program: 1-11A2SDL
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
  /qapi/student-adjustment-targets-waivers-substitutions-waivers:
    post:
      tags:
      - student-adjustment-targets-waivers-substitutions-waivers QAPI (Query by POST)
      summary: Return resources from SMASADJ
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_qapi_post_request'
            example:
              keyblckTermCode: 201520
              id: A00076810
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student-adjustment-targets-waivers-substitutions-waivers-1.0.0_qapi_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
        EllucianOAuthUserToken: []
components:
  schemas:
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_post_response:
      type: object
      properties:
        smrswpv:
          type: array
          items:
            type: object
            properties:
              programDesc:
                title: Program Description
                type: string
              maint:
                maxLength: 0
                type: string
              program:
                title: Program
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWPV_PROGRAM"
                x-lineageReferenceObject: SMRSWPV_PROGRAM
            x-lineageReferenceObject: smrswpv
        smrswav:
          type: array
          items:
            required:
            - crseNumb
            - subjCode
            type: object
            properties:
              area:
                title: Smrswav Area
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_AREA"
                x-lineageReferenceObject: SMRSWAV_AREA
              crseNumb:
                title: Smrswav Crse Numb
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
                x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
              actnCode:
                title: Smrswav Actn Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup\
                  \ lineage reference object : stvactn"
                x-lineageReferenceObject: SMRSWAV_ACTN_CODE
                x-lineageLookupReferenceObject: stvactn
              attrCode:
                title: Smrswav Attr Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup\
                  \ lineage reference object : stvattr"
                x-lineageReferenceObject: SMRSWAV_ATTR_CODE
                x-lineageLookupReferenceObject: stvattr
              credits:
                title: Smrswav Credits
                maxLength: 12
                type: number
                description: "Lineage reference object : SMRSWAV_CREDITS"
                x-lineageReferenceObject: SMRSWAV_CREDITS
              maint:
                maxLength: 0
                type: string
              subjCode:
                title: Smrswav Subj Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup\
                  \ lineage reference object : stvsubj"
                x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
                x-lineageLookupReferenceObject: stvsubj
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              group:
                title: Smrswav Group
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_GROUP"
                x-lineageReferenceObject: SMRSWAV_GROUP
            x-lineageReferenceObject: smrswav
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_post_request:
      required:
      - smrswavSubjCode
      - smrswavCrseNumb
      type: object
      properties:
        area:
          title: Smrswav Area
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_AREA"
          x-lineageReferenceObject: SMRSWAV_AREA
        actnCode:
          title: Smrswav Actn Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup lineage\
            \ reference object : stvactn"
          x-lineageReferenceObject: SMRSWAV_ACTN_CODE
          x-lineageLookupReferenceObject: stvactn
        attrCode:
          title: Smrswav Attr Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup lineage\
            \ reference object : stvattr"
          x-lineageReferenceObject: SMRSWAV_ATTR_CODE
          x-lineageLookupReferenceObject: stvattr
        smrswavCrseNumb:
          title: Smrswav Crse Numb
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
          x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
        credits:
          title: Smrswav Credits
          maxLength: 12
          type: number
          description: "Lineage reference object : SMRSWAV_CREDITS"
          x-lineageReferenceObject: SMRSWAV_CREDITS
        smrswavSubjCode:
          title: Smrswav Subj Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
          x-lineageLookupReferenceObject: stvsubj
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        program:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWPV_PROGRAM"
          x-lineageReferenceObject: SMRSWPV_PROGRAM
        group:
          title: Smrswav Group
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_GROUP"
          x-lineageReferenceObject: SMRSWAV_GROUP
      x-lineageReferenceObject: SMRSWPV
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_qapi_post_response:
      type: object
      properties:
        smrswpv:
          type: array
          items:
            type: object
            properties:
              programDesc:
                title: Program Description
                type: string
              maint:
                maxLength: 0
                type: string
              program:
                title: Program
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWPV_PROGRAM"
                x-lineageReferenceObject: SMRSWPV_PROGRAM
            x-lineageReferenceObject: smrswpv
        smrswav:
          type: array
          items:
            required:
            - crseNumb
            - subjCode
            type: object
            properties:
              area:
                title: Smrswav Area
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_AREA"
                x-lineageReferenceObject: SMRSWAV_AREA
              crseNumb:
                title: Smrswav Crse Numb
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
                x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
              actnCode:
                title: Smrswav Actn Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup\
                  \ lineage reference object : stvactn"
                x-lineageReferenceObject: SMRSWAV_ACTN_CODE
                x-lineageLookupReferenceObject: stvactn
              attrCode:
                title: Smrswav Attr Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup\
                  \ lineage reference object : stvattr"
                x-lineageReferenceObject: SMRSWAV_ATTR_CODE
                x-lineageLookupReferenceObject: stvattr
              credits:
                title: Smrswav Credits
                maxLength: 12
                type: number
                description: "Lineage reference object : SMRSWAV_CREDITS"
                x-lineageReferenceObject: SMRSWAV_CREDITS
              maint:
                maxLength: 0
                type: string
              subjCode:
                title: Smrswav Subj Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup\
                  \ lineage reference object : stvsubj"
                x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
                x-lineageLookupReferenceObject: stvsubj
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              group:
                title: Smrswav Group
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_GROUP"
                x-lineageReferenceObject: SMRSWAV_GROUP
            x-lineageReferenceObject: smrswav
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for
                  the primary data entity used to create the resource. This is useful
                  for referencing the source item through the applications administrative
                  user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: 'The detailed actionable error message. '
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_put_request:
      required:
      - criteria.subjCode
      - criteria.crseNumb
      - subjCode
      - crseNumb
      type: object
      properties:
        area:
          title: Smrswav Area
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_AREA"
          x-lineageReferenceObject: SMRSWAV_AREA
        criteria.program:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWPV_PROGRAM"
          x-lineageReferenceObject: SMRSWPV_PROGRAM
        criteria.actnCode:
          title: Smrswav Actn Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup lineage\
            \ reference object : stvactn"
          x-lineageReferenceObject: SMRSWAV_ACTN_CODE
          x-lineageLookupReferenceObject: stvactn
        attrCode:
          title: Smrswav Attr Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup lineage\
            \ reference object : stvattr"
          x-lineageReferenceObject: SMRSWAV_ATTR_CODE
          x-lineageLookupReferenceObject: stvattr
        criteria.crseNumb:
          title: Smrswav Crse Numb
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
          x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
        subjCode:
          title: Smrswav Subj Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
          x-lineageLookupReferenceObject: stvsubj
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        criteria.subjCode:
          title: Smrswav Subj Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
          x-lineageLookupReferenceObject: stvsubj
        program:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWPV_PROGRAM"
          x-lineageReferenceObject: SMRSWPV_PROGRAM
        crseNumb:
          title: Smrswav Crse Numb
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
          x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
        actnCode:
          title: Smrswav Actn Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup lineage\
            \ reference object : stvactn"
          x-lineageReferenceObject: SMRSWAV_ACTN_CODE
          x-lineageLookupReferenceObject: stvactn
        credits:
          title: Smrswav Credits
          maxLength: 12
          type: number
          description: "Lineage reference object : SMRSWAV_CREDITS"
          x-lineageReferenceObject: SMRSWAV_CREDITS
        criteria.attrCode:
          title: Smrswav Attr Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup lineage\
            \ reference object : stvattr"
          x-lineageReferenceObject: SMRSWAV_ATTR_CODE
          x-lineageLookupReferenceObject: stvattr
        criteria.group:
          title: Smrswav Group
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_GROUP"
          x-lineageReferenceObject: SMRSWAV_GROUP
        criteria.area:
          title: Smrswav Area
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_AREA"
          x-lineageReferenceObject: SMRSWAV_AREA
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.credits:
          title: Smrswav Credits
          maxLength: 12
          type: number
          description: "Lineage reference object : SMRSWAV_CREDITS"
          x-lineageReferenceObject: SMRSWAV_CREDITS
        group:
          title: Smrswav Group
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_GROUP"
          x-lineageReferenceObject: SMRSWAV_GROUP
      x-lineageReferenceObject: SMRSWPV
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_qapi_post_request:
      required:
      - subjCode
      - crseNumb
      type: object
      properties:
        area:
          title: Smrswav Area
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_AREA"
          x-lineageReferenceObject: SMRSWAV_AREA
        crseNumb:
          title: Smrswav Crse Numb
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
          x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
        actnCode:
          title: Smrswav Actn Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup lineage\
            \ reference object : stvactn"
          x-lineageReferenceObject: SMRSWAV_ACTN_CODE
          x-lineageLookupReferenceObject: stvactn
        attrCode:
          title: Smrswav Attr Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup lineage\
            \ reference object : stvattr"
          x-lineageReferenceObject: SMRSWAV_ATTR_CODE
          x-lineageLookupReferenceObject: stvattr
        credits:
          title: Smrswav Credits
          maxLength: 12
          type: number
          description: "Lineage reference object : SMRSWAV_CREDITS"
          x-lineageReferenceObject: SMRSWAV_CREDITS
        subjCode:
          title: Smrswav Subj Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup lineage\
            \ reference object : stvsubj"
          x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
          x-lineageLookupReferenceObject: stvsubj
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage\
            \ reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        program:
          title: Program
          maxLength: 30
          type: string
          description: "Lineage reference object : SMRSWPV_PROGRAM"
          x-lineageReferenceObject: SMRSWPV_PROGRAM
        group:
          title: Smrswav Group
          maxLength: 10
          type: string
          description: "Lineage reference object : SMRSWAV_GROUP"
          x-lineageReferenceObject: SMRSWAV_GROUP
      x-lineageReferenceObject: SMRSWPV
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_get_response:
      type: object
      properties:
        smrswpv:
          type: array
          items:
            type: object
            properties:
              programDesc:
                title: Program Description
                type: string
              maint:
                maxLength: 0
                type: string
              program:
                title: Program
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWPV_PROGRAM"
                x-lineageReferenceObject: SMRSWPV_PROGRAM
            x-lineageReferenceObject: smrswpv
        smrswav:
          type: array
          items:
            required:
            - crseNumb
            - subjCode
            type: object
            properties:
              area:
                title: Smrswav Area
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_AREA"
                x-lineageReferenceObject: SMRSWAV_AREA
              crseNumb:
                title: Smrswav Crse Numb
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
                x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
              actnCode:
                title: Smrswav Actn Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup\
                  \ lineage reference object : stvactn"
                x-lineageReferenceObject: SMRSWAV_ACTN_CODE
                x-lineageLookupReferenceObject: stvactn
              attrCode:
                title: Smrswav Attr Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup\
                  \ lineage reference object : stvattr"
                x-lineageReferenceObject: SMRSWAV_ATTR_CODE
                x-lineageLookupReferenceObject: stvattr
              credits:
                title: Smrswav Credits
                maxLength: 12
                type: number
                description: "Lineage reference object : SMRSWAV_CREDITS"
                x-lineageReferenceObject: SMRSWAV_CREDITS
              maint:
                maxLength: 0
                type: string
              subjCode:
                title: Smrswav Subj Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup\
                  \ lineage reference object : stvsubj"
                x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
                x-lineageLookupReferenceObject: stvsubj
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              group:
                title: Smrswav Group
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_GROUP"
                x-lineageReferenceObject: SMRSWAV_GROUP
            x-lineageReferenceObject: smrswav
    student-adjustment-targets-waivers-substitutions-waivers-1.0.0_put_response:
      type: object
      properties:
        smrswpv:
          type: array
          items:
            type: object
            properties:
              programDesc:
                title: Program Description
                type: string
              maint:
                maxLength: 0
                type: string
              program:
                title: Program
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWPV_PROGRAM"
                x-lineageReferenceObject: SMRSWPV_PROGRAM
            x-lineageReferenceObject: smrswpv
        smrswav:
          type: array
          items:
            required:
            - crseNumb
            - subjCode
            type: object
            properties:
              area:
                title: Smrswav Area
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_AREA"
                x-lineageReferenceObject: SMRSWAV_AREA
              crseNumb:
                title: Smrswav Crse Numb
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_CRSE_NUMB"
                x-lineageReferenceObject: SMRSWAV_CRSE_NUMB
              actnCode:
                title: Smrswav Actn Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ACTN_CODE, Lookup\
                  \ lineage reference object : stvactn"
                x-lineageReferenceObject: SMRSWAV_ACTN_CODE
                x-lineageLookupReferenceObject: stvactn
              attrCode:
                title: Smrswav Attr Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_ATTR_CODE, Lookup\
                  \ lineage reference object : stvattr"
                x-lineageReferenceObject: SMRSWAV_ATTR_CODE
                x-lineageLookupReferenceObject: stvattr
              credits:
                title: Smrswav Credits
                maxLength: 12
                type: number
                description: "Lineage reference object : SMRSWAV_CREDITS"
                x-lineageReferenceObject: SMRSWAV_CREDITS
              maint:
                maxLength: 0
                type: string
              subjCode:
                title: Smrswav Subj Code
                maxLength: 30
                type: string
                description: "Lineage reference object : SMRSWAV_SUBJ_CODE, Lookup\
                  \ lineage reference object : stvsubj"
                x-lineageReferenceObject: SMRSWAV_SUBJ_CODE
                x-lineageLookupReferenceObject: stvsubj
              courseAlias:
                title: Course Alias
                maxLength: 20
                type: string
              group:
                title: Smrswav Group
                maxLength: 10
                type: string
                description: "Lineage reference object : SMRSWAV_GROUP"
                x-lineageReferenceObject: SMRSWAV_GROUP
            x-lineageReferenceObject: smrswav
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer