openapi: 3.0.0
info:
  title: eu-hesa-course-catalog-identifier-details
  description: API for SOACCID administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SOACCID
  x-source-domain: Student
  x-source-title: Course Catalog Identifier Details (Europe - Hesa)
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/eu-hesa-course-catalog-identifier-details:
    get:
      tags:
        - eu-hesa-course-catalog-identifier-details
      summary: Return resources from SOACCID
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblockModId
          in: query
          required: false
          schema:
            type: string
        - name: keyblockCourseId
          in: query
          required: false
          schema:
            type: string
        - name: copyKeyblockModId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - eu-hesa-course-catalog-identifier-details
      summary: Updates an existing resource in SOACCID
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_put\
                _request"
            example:
              ssdtCodeFranInd: 2
              keyblockCourseId: 1181
              costCentreProportion: 1
              ssdtCodeHesaId: 5044
              copyKeyblockModId: 123
              ssdtCodeModSub: 100035
              modProportion: 6.4
              ssdtCodeCostCentre: 101
              keyblockModId: 123
              roleProportion: 86
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_put\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - eu-hesa-course-catalog-identifier-details
      summary: Creates a new resource in SOACCID
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_pos\
                t_request"
            example:
              ssdtCodeFranInd: 1
              keyblockCourseId: 1181
              ssdtCodeHesaId: 5057
              ssdtCodeModSub: 100035
              modProportion: 6.6
              ssdtCodeCostCentre: 103
              keyblockModId: 123
              roleProportion: 4
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_pos\
                    t_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/eu-hesa-course-catalog-identifier-details:
    post:
      tags:
        - eu-hesa-course-catalog-identifier-details QAPI (Query by POST)
      summary: Return resources from SOACCID
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_get\
                _request"
            example:
              keyblockCourseId: 1181
              copyKeyblockModId: 123
              keyblockModId: 123
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/eu-hesa-course-catalog-identifier-details-1.0.0_get\
                    _response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    eu-hesa-course-catalog-identifier-details-1.0.0_get_response:
      type: object
      properties:
        sobccid:
          type: array
          items:
            type: object
            properties:
              ssdtCodeCrdtPtsLvl:
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_PTS_LVL, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_PTS_LVL
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              fullTimeEquivalence:
                type: number
                description: "Lineage reference object : SOBCCID_FULL_TIME_EQUIVALENCE"
                x-lineageReferenceObject: SOBCCID_FULL_TIME_EQUIVALENCE
              SobccidSsdtCodeLangId:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_LANG_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_LANG_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SOBCCID_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SOBCCID_ACTIVITY_DATE
              ssdtCodeCrdtPtsLvlSt:
                type: string
              SobccidModuleTitle:
                type: string
                description: "Lineage reference object : SOBCCID_MODULE_TITLE"
                x-lineageReferenceObject: SOBCCID_MODULE_TITLE
              modCrdtVal:
                type: number
                description: "Lineage reference object : SOBCCID_MOD_CRDT_VAL"
                x-lineageReferenceObject: SOBCCID_MOD_CRDT_VAL
              ssdtCodeCrdtTraSchSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SOBCCID_USER_ID"
                x-lineageReferenceObject: SOBCCID_USER_ID
              modId:
                type: string
                description: "Lineage reference object : SOBCCID_MOD_ID"
                x-lineageReferenceObject: SOBCCID_MOD_ID
              SobccidSsdtCodeLangIdSt:
                type: string
              ssdtCodeCrdtTraSch:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_TRA_SCH, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_TRA_SCH
                x-lineageLookupReferenceObject: skvssdt,skvssdt
            x-lineageReferenceObject: sobccid
        sorccms:
          type: array
          items:
            required:
              - ssdtCodeModSub
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCMS_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCMS_ACTIVITY_DATE
              ssdtCodeModSubSt:
                type: string
              ssdtCodeModSub:
                type: string
                description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              modProportion:
                type: number
                description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
                x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCMS_USER_ID"
                x-lineageReferenceObject: SORCCMS_USER_ID
            x-lineageReferenceObject: sorccms
        sorccdc:
          type: array
          items:
            required:
              - ssdtCodeCostCentre
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDC_ACTIVITY_DATE
              costCentreProportion:
                type: number
                description: "Lineage reference object : SORCCDC_COST_CENTRE_PROPORTION"
                x-lineageReferenceObject: SORCCDC_COST_CENTRE_PROPORTION
              ssdtCodeCostCentreSt:
                type: string
              ssdtCodeCostCentre:
                type: string
                description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
                x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDC_USER_ID"
                x-lineageReferenceObject: SORCCDC_USER_ID
            x-lineageReferenceObject: sorccdc
        sorccdr:
          type: array
          items:
            required:
              - ssdtCodeHesaId
            type: object
            properties:
              ssdtCodeFranInd:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDR_ACTIVITY_DATE
              ssdtCodeHesaIdSt:
                type: string
              ssdtCodeHesaId:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              ssdtCodeFranIndSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDR_USER_ID"
                x-lineageReferenceObject: SORCCDR_USER_ID
              roleProportion:
                type: number
                description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
                x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
            x-lineageReferenceObject: sorccdr
    eu-hesa-course-catalog-identifier-details-1.0.0_post_request:
      required:
        - ssdtCodeModSub
        - ssdtCodeCostCentre
        - ssdtCodeHesaId
      type: object
      properties:
        ssdtCodeFranInd:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        keyblockCourseId:
          type: string
          description: "Lineage reference object : keyblockCourseId"
          x-lineageReferenceObject: keyblockCourseId
        ssdtCodeHesaId:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        copyKeyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : copyKeyblockModId, Lookup lineage
            reference object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: copyKeyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
        ssdtCodeModSub:
          type: string
          description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        modProportion:
          type: number
          description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
          x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
        ssdtCodeCostCentre:
          type: string
          description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
          x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
        keyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : keyblockModId, Lookup lineage reference
            object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: keyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
        roleProportion:
          type: number
          description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
          x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
      x-lineageReferenceObject: SORCCDR
    eu-hesa-course-catalog-identifier-details-1.0.0_put_response:
      type: object
      properties:
        sobccid:
          type: array
          items:
            type: object
            properties:
              ssdtCodeCrdtPtsLvl:
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_PTS_LVL, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_PTS_LVL
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              fullTimeEquivalence:
                type: number
                description: "Lineage reference object : SOBCCID_FULL_TIME_EQUIVALENCE"
                x-lineageReferenceObject: SOBCCID_FULL_TIME_EQUIVALENCE
              SobccidSsdtCodeLangId:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_LANG_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_LANG_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SOBCCID_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SOBCCID_ACTIVITY_DATE
              ssdtCodeCrdtPtsLvlSt:
                type: string
              SobccidModuleTitle:
                type: string
                description: "Lineage reference object : SOBCCID_MODULE_TITLE"
                x-lineageReferenceObject: SOBCCID_MODULE_TITLE
              modCrdtVal:
                type: number
                description: "Lineage reference object : SOBCCID_MOD_CRDT_VAL"
                x-lineageReferenceObject: SOBCCID_MOD_CRDT_VAL
              ssdtCodeCrdtTraSchSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SOBCCID_USER_ID"
                x-lineageReferenceObject: SOBCCID_USER_ID
              modId:
                type: string
                description: "Lineage reference object : SOBCCID_MOD_ID"
                x-lineageReferenceObject: SOBCCID_MOD_ID
              SobccidSsdtCodeLangIdSt:
                type: string
              ssdtCodeCrdtTraSch:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_TRA_SCH, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_TRA_SCH
                x-lineageLookupReferenceObject: skvssdt,skvssdt
            x-lineageReferenceObject: sobccid
        sorccms:
          type: array
          items:
            required:
              - ssdtCodeModSub
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCMS_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCMS_ACTIVITY_DATE
              ssdtCodeModSubSt:
                type: string
              ssdtCodeModSub:
                type: string
                description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              modProportion:
                type: number
                description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
                x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCMS_USER_ID"
                x-lineageReferenceObject: SORCCMS_USER_ID
            x-lineageReferenceObject: sorccms
        sorccdc:
          type: array
          items:
            required:
              - ssdtCodeCostCentre
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDC_ACTIVITY_DATE
              costCentreProportion:
                type: number
                description: "Lineage reference object : SORCCDC_COST_CENTRE_PROPORTION"
                x-lineageReferenceObject: SORCCDC_COST_CENTRE_PROPORTION
              ssdtCodeCostCentreSt:
                type: string
              ssdtCodeCostCentre:
                type: string
                description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
                x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDC_USER_ID"
                x-lineageReferenceObject: SORCCDC_USER_ID
            x-lineageReferenceObject: sorccdc
        sorccdr:
          type: array
          items:
            required:
              - ssdtCodeHesaId
            type: object
            properties:
              ssdtCodeFranInd:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDR_ACTIVITY_DATE
              ssdtCodeHesaIdSt:
                type: string
              ssdtCodeHesaId:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              ssdtCodeFranIndSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDR_USER_ID"
                x-lineageReferenceObject: SORCCDR_USER_ID
              roleProportion:
                type: number
                description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
                x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
            x-lineageReferenceObject: sorccdr
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    eu-hesa-course-catalog-identifier-details-1.0.0_qapi_post:
      type: object
      properties:
        keyblockModId:
          type: string
        keyblockCourseId:
          type: string
        copyKeyblockModId:
          type: string
    eu-hesa-course-catalog-identifier-details-1.0.0_post_response:
      type: object
      properties:
        sobccid:
          type: array
          items:
            type: object
            properties:
              ssdtCodeCrdtPtsLvl:
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_PTS_LVL, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_PTS_LVL
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              fullTimeEquivalence:
                type: number
                description: "Lineage reference object : SOBCCID_FULL_TIME_EQUIVALENCE"
                x-lineageReferenceObject: SOBCCID_FULL_TIME_EQUIVALENCE
              SobccidSsdtCodeLangId:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_LANG_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_LANG_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SOBCCID_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SOBCCID_ACTIVITY_DATE
              ssdtCodeCrdtPtsLvlSt:
                type: string
              SobccidModuleTitle:
                type: string
                description: "Lineage reference object : SOBCCID_MODULE_TITLE"
                x-lineageReferenceObject: SOBCCID_MODULE_TITLE
              modCrdtVal:
                type: number
                description: "Lineage reference object : SOBCCID_MOD_CRDT_VAL"
                x-lineageReferenceObject: SOBCCID_MOD_CRDT_VAL
              ssdtCodeCrdtTraSchSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SOBCCID_USER_ID"
                x-lineageReferenceObject: SOBCCID_USER_ID
              modId:
                type: string
                description: "Lineage reference object : SOBCCID_MOD_ID"
                x-lineageReferenceObject: SOBCCID_MOD_ID
              SobccidSsdtCodeLangIdSt:
                type: string
              ssdtCodeCrdtTraSch:
                maxLength: 2
                type: string
                description: "Lineage reference object : SOBCCID_SSDT_CODE_CRDT_TRA_SCH, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SOBCCID_SSDT_CODE_CRDT_TRA_SCH
                x-lineageLookupReferenceObject: skvssdt,skvssdt
            x-lineageReferenceObject: sobccid
        sorccms:
          type: array
          items:
            required:
              - ssdtCodeModSub
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCMS_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCMS_ACTIVITY_DATE
              ssdtCodeModSubSt:
                type: string
              ssdtCodeModSub:
                type: string
                description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              modProportion:
                type: number
                description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
                x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCMS_USER_ID"
                x-lineageReferenceObject: SORCCMS_USER_ID
            x-lineageReferenceObject: sorccms
        sorccdc:
          type: array
          items:
            required:
              - ssdtCodeCostCentre
            type: object
            properties:
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDC_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDC_ACTIVITY_DATE
              costCentreProportion:
                type: number
                description: "Lineage reference object : SORCCDC_COST_CENTRE_PROPORTION"
                x-lineageReferenceObject: SORCCDC_COST_CENTRE_PROPORTION
              ssdtCodeCostCentreSt:
                type: string
              ssdtCodeCostCentre:
                type: string
                description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
                x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDC_USER_ID"
                x-lineageReferenceObject: SORCCDC_USER_ID
            x-lineageReferenceObject: sorccdc
        sorccdr:
          type: array
          items:
            required:
              - ssdtCodeHesaId
            type: object
            properties:
              ssdtCodeFranInd:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              activityDate:
                maxLength: 26
                type: string
                description: "Lineage reference object : SORCCDR_ACTIVITY_DATE"
                format: date-time
                x-lineageReferenceObject: SORCCDR_ACTIVITY_DATE
              ssdtCodeHesaIdSt:
                type: string
              ssdtCodeHesaId:
                type: string
                description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
                  lineage reference object : skvssdt,skvssdt"
                x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
                x-lineageLookupReferenceObject: skvssdt,skvssdt
              ssdtCodeFranIndSt:
                type: string
              userId:
                maxLength: 30
                type: string
                description: "Lineage reference object : SORCCDR_USER_ID"
                x-lineageReferenceObject: SORCCDR_USER_ID
              roleProportion:
                type: number
                description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
                x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
            x-lineageReferenceObject: sorccdr
    eu-hesa-course-catalog-identifier-details-1.0.0_get_request:
      type: object
      properties:
        keyblockCourseId:
          type: string
          description: "Lineage reference object : keyblockCourseId"
          x-lineageReferenceObject: keyblockCourseId
        copyKeyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : copyKeyblockModId, Lookup lineage
            reference object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: copyKeyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
        keyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : keyblockModId, Lookup lineage reference
            object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: keyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
      x-lineageReferenceObject: KEY_BLOCK
    eu-hesa-course-catalog-identifier-details-1.0.0_put_request:
      required:
        - criteria.ssdtCodeModSub
        - ssdtCodeModSub
        - criteria.ssdtCodeCostCentre
        - ssdtCodeCostCentre
        - criteria.ssdtCodeHesaId
        - ssdtCodeHesaId
      type: object
      properties:
        ssdtCodeFranInd:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        keyblockCourseId:
          type: string
          description: "Lineage reference object : keyblockCourseId"
          x-lineageReferenceObject: keyblockCourseId
        criteria.userId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SORCCMS_USER_ID"
          x-lineageReferenceObject: SORCCMS_USER_ID
        criteria.activityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : SORCCMS_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORCCMS_ACTIVITY_DATE
        criteria.sorccdcActivityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : SORCCDC_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORCCDC_ACTIVITY_DATE
        criteria.sorccdrUserId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SORCCDR_USER_ID"
          x-lineageReferenceObject: SORCCDR_USER_ID
        ssdtCodeCostCentre:
          type: string
          description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
          x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
        criteria.ssdtCodeCostCentre:
          type: string
          description: "Lineage reference object : SORCCDC_SSDT_CODE_COST_CENTRE"
          x-lineageReferenceObject: SORCCDC_SSDT_CODE_COST_CENTRE
        criteria.roleProportion:
          type: number
          description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
          x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
        criteria.ssdtCodeCostCentreSt:
          type: string
        criteria.ssdtCodeModSub:
          type: string
          description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        criteria.sorccdcUserId:
          maxLength: 30
          type: string
          description: "Lineage reference object : SORCCDC_USER_ID"
          x-lineageReferenceObject: SORCCDC_USER_ID
        copyKeyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : copyKeyblockModId, Lookup lineage
            reference object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: copyKeyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
        ssdtCodeModSub:
          type: string
          description: "Lineage reference object : SORCCMS_SSDT_CODE_MOD_SUB, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCMS_SSDT_CODE_MOD_SUB
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        criteria.ssdtCodeFranIndSt:
          type: string
        roleProportion:
          type: number
          description: "Lineage reference object : SORCCDR_ROLE_PROPORTION"
          x-lineageReferenceObject: SORCCDR_ROLE_PROPORTION
        criteria.sorccdrActivityDate:
          maxLength: 26
          type: string
          description: "Lineage reference object : SORCCDR_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORCCDR_ACTIVITY_DATE
        costCentreProportion:
          type: number
          description: "Lineage reference object : SORCCDC_COST_CENTRE_PROPORTION"
          x-lineageReferenceObject: SORCCDC_COST_CENTRE_PROPORTION
        criteria.modProportion:
          type: number
          description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
          x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
        criteria.ssdtCodeHesaIdSt:
          type: string
        modProportion:
          type: number
          description: "Lineage reference object : SORCCMS_MOD_PROPORTION"
          x-lineageReferenceObject: SORCCMS_MOD_PROPORTION
        criteria.costCentreProportion:
          type: number
          description: "Lineage reference object : SORCCDC_COST_CENTRE_PROPORTION"
          x-lineageReferenceObject: SORCCDC_COST_CENTRE_PROPORTION
        keyblockModId:
          maxLength: 50
          type: string
          description: "Lineage reference object : keyblockModId, Lookup lineage reference
            object : SOBCCID,SCBCRSE"
          x-lineageReferenceObject: keyblockModId
          x-lineageLookupReferenceObject: SOBCCID,SCBCRSE
        ssdtCodeHesaId:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        criteria.ssdtCodeFranInd:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_FRAN_IND, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_FRAN_IND
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        criteria.ssdtCodeHesaId:
          type: string
          description: "Lineage reference object : SORCCDR_SSDT_CODE_HESA_ID, Lookup
            lineage reference object : skvssdt,skvssdt"
          x-lineageReferenceObject: SORCCDR_SSDT_CODE_HESA_ID
          x-lineageLookupReferenceObject: skvssdt,skvssdt
        criteria.ssdtCodeModSubSt:
          type: string
      x-lineageReferenceObject: SORCCDR
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
