openapi: 3.0.0
info:
  title: student-withdrawal
  description: API for SFAWDRL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: SFAWDRL
  x-source-domain: Student
  x-source-title: Student Withdrawal Form
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/student-withdrawal:
    get:
      tags:
        - student-withdrawal
      summary: Return resources from SFAWDRL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma separated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: keyblckTermCode
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-withdrawal-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - student-withdrawal
      summary: Updates an existing resource in SFAWDRL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-withdrawal-1.0.0_put_request"
            example:
              enrlEndDate: 1994-12-16
              percentAttend: 84.5
              otherCosts: c
              wdrlCode: "01"
              enrlDays: 110
              keyblckTermCode: 199510
              effWdrlDate: 1994-11-29
              attendBreakDays: 0
              tivInd: Y
              sfrwdrlTivInd: N
              enrlStartDate: 1994-08-29
              enrlBreakDays: 0
              comment: dcdcsczczxthis is a change
              id: 210009508
              attendDays: 93
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-withdrawal-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - student-withdrawal
      summary: Creates a new resource in SFAWDRL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-withdrawal-1.0.0_post_request"
            example:
              enrlEndDate: 2022-01-01
              percentAttend: 1
              otherCosts: 2
              wdrlCode: Y
              enrlDays: 2
              keyblckTermCode: 199510
              effWdrlDate: 2022-01-01
              attendBreakDays: 1
              tivInd: N
              enrlStartDate: 2002-01-01
              enrlBreakDays: 1
              id: 210009508
              attendDays: 2
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-withdrawal-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/student-withdrawal:
    post:
      tags:
        - student-withdrawal QAPI (Query by POST)
      summary: Return resources from SFAWDRL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/student-withdrawal-1.0.0_qapi_post_request"
            example:
              keyblckTermCode: 199510
              id: 210009508
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/student-withdrawal-1.0.0_qapi_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    student-withdrawal-1.0.0_qapi_post_response:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        originalCharges:
          title: Original Charges
          maxLength: 18
          type: number
          description: "Lineage reference object : SFRWDRL_ORIGINAL_CHARGES"
          x-lineageReferenceObject: SFRWDRL_ORIGINAL_CHARGES
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        seqNo:
          title: Sequence Number
          type: number
          description: "Lineage reference object : SFRWDRL_SEQ_NO"
          x-lineageReferenceObject: SFRWDRL_SEQ_NO
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        processedInd:
          title: Processed Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_PROCESSED_IND"
          x-lineageReferenceObject: SFRWDRL_PROCESSED_IND
        wdrlDesc:
          type: string
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        estsCode:
          title: Current Enrollment Status
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_CODE"
          x-lineageReferenceObject: SFRWDRL_ESTS_CODE
        estsDate:
          title: Enrollment Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ESTS_DATE
        activityDate:
          title: Gortctl Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ACTIVITY_DATE
        estsDesc:
          type: string
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        comment:
          title: Comment
          maxLength: 240
          type: string
          description: "Lineage reference object : SFRWDRL_COMMENT"
          x-lineageReferenceObject: SFRWDRL_COMMENT
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
        user:
          title: Gortctl User Id
          type: string
          description: "Lineage reference object : SFRWDRL_USER"
          x-lineageReferenceObject: SFRWDRL_USER
      x-lineageReferenceObject: sfrwdrl
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    student-withdrawal-1.0.0_post_request:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
      x-lineageReferenceObject: SFRWDRL
    student-withdrawal-1.0.0_get_response:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        originalCharges:
          title: Original Charges
          maxLength: 18
          type: number
          description: "Lineage reference object : SFRWDRL_ORIGINAL_CHARGES"
          x-lineageReferenceObject: SFRWDRL_ORIGINAL_CHARGES
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        seqNo:
          title: Sequence Number
          type: number
          description: "Lineage reference object : SFRWDRL_SEQ_NO"
          x-lineageReferenceObject: SFRWDRL_SEQ_NO
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        processedInd:
          title: Processed Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_PROCESSED_IND"
          x-lineageReferenceObject: SFRWDRL_PROCESSED_IND
        wdrlDesc:
          type: string
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        estsCode:
          title: Current Enrollment Status
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_CODE"
          x-lineageReferenceObject: SFRWDRL_ESTS_CODE
        estsDate:
          title: Enrollment Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ESTS_DATE
        activityDate:
          title: Gortctl Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ACTIVITY_DATE
        estsDesc:
          type: string
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        comment:
          title: Comment
          maxLength: 240
          type: string
          description: "Lineage reference object : SFRWDRL_COMMENT"
          x-lineageReferenceObject: SFRWDRL_COMMENT
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
        user:
          title: Gortctl User Id
          type: string
          description: "Lineage reference object : SFRWDRL_USER"
          x-lineageReferenceObject: SFRWDRL_USER
      x-lineageReferenceObject: sfrwdrl
    student-withdrawal-1.0.0_put_response:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        originalCharges:
          title: Original Charges
          maxLength: 18
          type: number
          description: "Lineage reference object : SFRWDRL_ORIGINAL_CHARGES"
          x-lineageReferenceObject: SFRWDRL_ORIGINAL_CHARGES
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        seqNo:
          title: Sequence Number
          type: number
          description: "Lineage reference object : SFRWDRL_SEQ_NO"
          x-lineageReferenceObject: SFRWDRL_SEQ_NO
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        processedInd:
          title: Processed Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_PROCESSED_IND"
          x-lineageReferenceObject: SFRWDRL_PROCESSED_IND
        wdrlDesc:
          type: string
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        estsCode:
          title: Current Enrollment Status
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_CODE"
          x-lineageReferenceObject: SFRWDRL_ESTS_CODE
        estsDate:
          title: Enrollment Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ESTS_DATE
        activityDate:
          title: Gortctl Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ACTIVITY_DATE
        estsDesc:
          type: string
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        comment:
          title: Comment
          maxLength: 240
          type: string
          description: "Lineage reference object : SFRWDRL_COMMENT"
          x-lineageReferenceObject: SFRWDRL_COMMENT
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
        user:
          title: Gortctl User Id
          type: string
          description: "Lineage reference object : SFRWDRL_USER"
          x-lineageReferenceObject: SFRWDRL_USER
      x-lineageReferenceObject: sfrwdrl
    student-withdrawal-1.0.0_put_request:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        comment:
          title: Comment
          maxLength: 240
          type: string
          description: "Lineage reference object : SFRWDRL_COMMENT"
          x-lineageReferenceObject: SFRWDRL_COMMENT
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
      x-lineageReferenceObject: SFRWDRL
    student-withdrawal-1.0.0_post_response:
      type: object
      properties:
        enrlEndDate:
          title: Enrollment End Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_END_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_END_DATE
        otherCosts:
          title: Other Costs
          maxLength: 17
          type: number
          description: "Lineage reference object : SFRWDRL_OTHER_COSTS"
          x-lineageReferenceObject: SFRWDRL_OTHER_COSTS
        percentAttend:
          title: Percent Attended
          maxLength: 5
          type: number
          description: "Lineage reference object : SFRWDRL_PERCENT_ATTEND"
          x-lineageReferenceObject: SFRWDRL_PERCENT_ATTEND
        wdrlCode:
          title: Withdrawal Code
          maxLength: 30
          type: string
          description: "Lineage reference object : SFRWDRL_WDRL_CODE, Lookup lineage
            reference object : stvwdrl"
          x-lineageReferenceObject: SFRWDRL_WDRL_CODE
          x-lineageLookupReferenceObject: stvwdrl
        originalCharges:
          title: Original Charges
          maxLength: 18
          type: number
          description: "Lineage reference object : SFRWDRL_ORIGINAL_CHARGES"
          x-lineageReferenceObject: SFRWDRL_ORIGINAL_CHARGES
        enrlDays:
          title: Days In Period
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_DAYS
        seqNo:
          title: Sequence Number
          type: number
          description: "Lineage reference object : SFRWDRL_SEQ_NO"
          x-lineageReferenceObject: SFRWDRL_SEQ_NO
        attendBreakDays:
          title: Attendance Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_BREAK_DAYS
        effWdrlDate:
          title: Effective Withdrawal Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_EFF_WDRL_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_EFF_WDRL_DATE
        processedInd:
          title: Processed Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_PROCESSED_IND"
          x-lineageReferenceObject: SFRWDRL_PROCESSED_IND
        wdrlDesc:
          type: string
        tivInd:
          title: Title IV Record Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : SFRWDRL_TIV_IND"
          x-lineageReferenceObject: SFRWDRL_TIV_IND
        estsCode:
          title: Current Enrollment Status
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_CODE"
          x-lineageReferenceObject: SFRWDRL_ESTS_CODE
        estsDate:
          title: Enrollment Status Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ESTS_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ESTS_DATE
        activityDate:
          title: Gortctl Activity Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ACTIVITY_DATE
        estsDesc:
          type: string
        enrlBreakDays:
          title: Enrollment Break Days
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ENRL_BREAK_DAYS"
          x-lineageReferenceObject: SFRWDRL_ENRL_BREAK_DAYS
        enrlStartDate:
          title: Enrollment Start Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SFRWDRL_ENRL_START_DATE"
          format: date-time
          x-lineageReferenceObject: SFRWDRL_ENRL_START_DATE
        comment:
          title: Comment
          maxLength: 240
          type: string
          description: "Lineage reference object : SFRWDRL_COMMENT"
          x-lineageReferenceObject: SFRWDRL_COMMENT
        attendDays:
          title: Days Attended
          maxLength: 3
          type: number
          description: "Lineage reference object : SFRWDRL_ATTEND_DAYS"
          x-lineageReferenceObject: SFRWDRL_ATTEND_DAYS
        user:
          title: Gortctl User Id
          type: string
          description: "Lineage reference object : SFRWDRL_USER"
          x-lineageReferenceObject: SFRWDRL_USER
      x-lineageReferenceObject: sfrwdrl
    student-withdrawal-1.0.0_qapi_post_request:
      type: object
      properties:
        keyblckTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblckTermCode
          x-lineageLookupReferenceObject: stvterm
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
      x-lineageReferenceObject: KEY_BLOCK
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
