openapi: 3.0.0
info:
  title: direct-cash-receipt
  description: API for FGADCSR administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: FGADCSR
  x-source-domain: Finance
  x-source-title: Direct Cash Receipt
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/direct-cash-receipt:
    get:
      tags:
        - direct-cash-receipt
      summary: Return resources from FGADCSR
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: documentNumber
          in: query
          required: false
          schema:
            type: string
        - name: vendor
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-cash-receipt-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - direct-cash-receipt
      summary: Updates an existing resource in FGADCSR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-cash-receipt-1.0.0_put_request"
            example:
              documentNumber: 121562
              vendor: V7
              seqNum: 4
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-cash-receipt-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - direct-cash-receipt
      summary: Creates a new resource in FGADCSR
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-cash-receipt-1.0.0_post_request"
            example:
              bankCode: A1
              documentNumber: 121562
              vendor: V7
              seqNum: 1
              transDesc: test
              transAmt: 100
              coasCode: B
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-cash-receipt-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/direct-cash-receipt:
    post:
      tags:
        - direct-cash-receipt QAPI (Query by POST)
      summary: Return resources from FGADCSR
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/direct-cash-receipt-1.0.0_get_request"
            example:
              documentNumber: 121562
              vendor: V7
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/direct-cash-receipt-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    direct-cash-receipt-1.0.0_post_response:
      type: object
      properties:
        fgbcshh:
          type: array
          items:
            required:
              - transDate
            type: object
            properties:
              collectTaxDesc:
                maxLength: 35
                type: string
              transDate:
                title: Transaction Date
                maxLength: 26
                type: string
                description: "Lineage reference object : FGBCSHH_TRANS_DATE"
                format: date-time
                x-lineageReferenceObject: FGBCSHH_TRANS_DATE
              nsfOnOffInd:
                title: NSF Checking
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHH_NSF_ON_OFF_IND"
                x-lineageReferenceObject: FGBCSHH_NSF_ON_OFF_IND
              displayCollectTax:
                title: Collects Tax
                maxLength: 1
                type: string
              docAmt:
                title: Document Total
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHH_DOC_AMT"
                x-lineageReferenceObject: FGBCSHH_DOC_AMT
            x-lineageReferenceObject: fgbcshh
        fgbcshd:
          type: array
          items:
            required:
              - bankCode
              - coasCode
              - seqNum
              - transAmt
              - transDesc
            type: object
            properties:
              progTitle:
                maxLength: 35
                type: string
              fundTitle:
                maxLength: 35
                type: string
              currCode:
                title: Currency
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
                  reference object : gtvcurr"
                x-lineageReferenceObject: FGBCSHD_CURR_CODE
                x-lineageLookupReferenceObject: gtvcurr
              tgrpCode:
                title: Tax Group
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
                  reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
                x-lineageReferenceObject: FGBCSHD_TGRP_CODE
                x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
              coasCode:
                title: COA
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
                  reference object : ftvcoas"
                x-lineageReferenceObject: FGBCSHD_COAS_CODE
                x-lineageLookupReferenceObject: ftvcoas
              acctTitle:
                maxLength: 35
                type: string
              locnCode:
                title: Locn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_LOCN_CODE"
                x-lineageReferenceObject: FGBCSHD_LOCN_CODE
              orgnCode:
                title: Orgn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ORGN_CODE"
                x-lineageReferenceObject: FGBCSHD_ORGN_CODE
              fundCode:
                title: Fund
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_FUND_CODE"
                x-lineageReferenceObject: FGBCSHD_FUND_CODE
              actvTitle:
                maxLength: 35
                type: string
              statusInd:
                title: Status
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_STATUS_IND"
                x-lineageReferenceObject: FGBCSHD_STATUS_IND
              progCode:
                title: Prog
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_PROG_CODE"
                x-lineageReferenceObject: FGBCSHD_PROG_CODE
              transAmt:
                title: Amount
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHD_TRANS_AMT"
                x-lineageReferenceObject: FGBCSHD_TRANS_AMT
              docRefNum:
                title: Document Reference
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
                x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
              displayTaxDesc:
                maxLength: 35
                type: string
              locnTitle:
                maxLength: 35
                type: string
              actvCode:
                title: Actv
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACTV_CODE"
                x-lineageReferenceObject: FGBCSHD_ACTV_CODE
              drCrInd:
                title: Debit/Credit
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_DR_CR_IND"
                x-lineageReferenceObject: FGBCSHD_DR_CR_IND
              depNum:
                title: Deposit
                maxLength: 8
                type: string
                description: "Lineage reference object : FGBCSHD_DEP_NUM"
                x-lineageReferenceObject: FGBCSHD_DEP_NUM
              bankCode:
                title: Bank
                maxLength: 30
                type: string
                description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
                  reference object : gxvbank"
                x-lineageReferenceObject: FGBCSHD_BANK_CODE
                x-lineageLookupReferenceObject: gxvbank
              seqNum:
                title: Sequence
                maxLength: 4
                type: number
                description: "Lineage reference object : FGBCSHD_SEQ_NUM"
                x-lineageReferenceObject: FGBCSHD_SEQ_NUM
              acciCode:
                title: Index
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
                  reference object : ftvacci"
                x-lineageReferenceObject: FGBCSHD_ACCI_CODE
                x-lineageLookupReferenceObject: ftvacci
              acctCode:
                title: Acct
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCT_CODE"
                x-lineageReferenceObject: FGBCSHD_ACCT_CODE
              orgnTitle:
                maxLength: 35
                type: string
              fsyrCode:
                title: Year
                maxLength: 2
                type: string
                description: "Lineage reference object : FGBCSHD_FSYR_CODE"
                x-lineageReferenceObject: FGBCSHD_FSYR_CODE
              transDesc:
                title: Description
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_TRANS_DESC"
                x-lineageReferenceObject: FGBCSHD_TRANS_DESC
              abalOverride:
                title: NSF Override
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
                x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
              acciTitle:
                maxLength: 35
                type: string
              distPct:
                title: Percent
                maxLength: 8
                type: number
                description: "Lineage reference object : FGBCSHD_DIST_PCT"
                x-lineageReferenceObject: FGBCSHD_DIST_PCT
              coasTitle:
                maxLength: 35
                type: string
            x-lineageReferenceObject: fgbcshd
    direct-cash-receipt-1.0.0_put_request:
      required:
        - transDate
        - criteria.seqNum
        - criteria.coasCode
        - criteria.transAmt
        - criteria.transDesc
        - criteria.bankCode
        - seqNum
        - coasCode
        - transAmt
        - transDesc
        - bankCode
      type: object
      properties:
        criteria.distPct:
          title: Percent
          maxLength: 8
          type: number
          description: "Lineage reference object : FGBCSHD_DIST_PCT"
          x-lineageReferenceObject: FGBCSHD_DIST_PCT
        tgrpCode:
          title: Tax Group
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
            reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
          x-lineageReferenceObject: FGBCSHD_TGRP_CODE
          x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
        currCode:
          title: Currency
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
            reference object : gtvcurr"
          x-lineageReferenceObject: FGBCSHD_CURR_CODE
          x-lineageLookupReferenceObject: gtvcurr
        criteria.statusInd:
          title: Status
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_STATUS_IND"
          x-lineageReferenceObject: FGBCSHD_STATUS_IND
        criteria.transDesc:
          title: Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_TRANS_DESC"
          x-lineageReferenceObject: FGBCSHD_TRANS_DESC
        documentNumber:
          title: Document Number
          maxLength: 30
          type: string
          description: "Lineage reference object : documentNumber"
          x-lineageReferenceObject: documentNumber
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FGBCSHD_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        criteria.progCode:
          title: Prog
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_PROG_CODE"
          x-lineageReferenceObject: FGBCSHD_PROG_CODE
        locnCode:
          title: Locn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_LOCN_CODE"
          x-lineageReferenceObject: FGBCSHD_LOCN_CODE
        orgnCode:
          title: Orgn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ORGN_CODE"
          x-lineageReferenceObject: FGBCSHD_ORGN_CODE
        criteria.docRefNum:
          title: Document Reference
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
          x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
        criteria.displayTaxDesc:
          maxLength: 35
          type: string
        criteria.acciCode:
          title: Index
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
            reference object : ftvacci"
          x-lineageReferenceObject: FGBCSHD_ACCI_CODE
          x-lineageLookupReferenceObject: ftvacci
        criteria.depNum:
          title: Deposit
          maxLength: 8
          type: string
          description: "Lineage reference object : FGBCSHD_DEP_NUM"
          x-lineageReferenceObject: FGBCSHD_DEP_NUM
        fundCode:
          title: Fund
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_FUND_CODE"
          x-lineageReferenceObject: FGBCSHD_FUND_CODE
        vendor:
          title: Vendor Code
          maxLength: 9
          type: string
          description: "Lineage reference object : keyBlockVendor"
          x-lineageReferenceObject: keyBlockVendor
        transDate:
          title: Transaction Date
          maxLength: 26
          type: string
          description: "Lineage reference object : FGBCSHH_TRANS_DATE"
          format: date-time
          x-lineageReferenceObject: FGBCSHH_TRANS_DATE
        progCode:
          title: Prog
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_PROG_CODE"
          x-lineageReferenceObject: FGBCSHD_PROG_CODE
        transAmt:
          title: Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FGBCSHD_TRANS_AMT"
          x-lineageReferenceObject: FGBCSHD_TRANS_AMT
        criteria.transAmt:
          title: Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FGBCSHD_TRANS_AMT"
          x-lineageReferenceObject: FGBCSHD_TRANS_AMT
        docRefNum:
          title: Document Reference
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
          x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
        criteria.seqNum:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : FGBCSHD_SEQ_NUM"
          x-lineageReferenceObject: FGBCSHD_SEQ_NUM
        criteria.coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FGBCSHD_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        displayTaxDesc:
          maxLength: 35
          type: string
        actvCode:
          title: Actv
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACTV_CODE"
          x-lineageReferenceObject: FGBCSHD_ACTV_CODE
        drCrInd:
          title: Debit/Credit
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_DR_CR_IND"
          x-lineageReferenceObject: FGBCSHD_DR_CR_IND
        depNum:
          title: Deposit
          maxLength: 8
          type: string
          description: "Lineage reference object : FGBCSHD_DEP_NUM"
          x-lineageReferenceObject: FGBCSHD_DEP_NUM
        bankCode:
          title: Bank
          maxLength: 30
          type: string
          description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FGBCSHD_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
        criteria.locnCode:
          title: Locn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_LOCN_CODE"
          x-lineageReferenceObject: FGBCSHD_LOCN_CODE
        criteria.fundCode:
          title: Fund
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_FUND_CODE"
          x-lineageReferenceObject: FGBCSHD_FUND_CODE
        criteria.acctCode:
          title: Acct
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCT_CODE"
          x-lineageReferenceObject: FGBCSHD_ACCT_CODE
        criteria.abalOverride:
          title: NSF Override
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
          x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
        seqNum:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : FGBCSHD_SEQ_NUM"
          x-lineageReferenceObject: FGBCSHD_SEQ_NUM
        acciCode:
          title: Index
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
            reference object : ftvacci"
          x-lineageReferenceObject: FGBCSHD_ACCI_CODE
          x-lineageLookupReferenceObject: ftvacci
        criteria.actvCode:
          title: Actv
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACTV_CODE"
          x-lineageReferenceObject: FGBCSHD_ACTV_CODE
        fgbcshdAbalOverride:
          title: NSF Override
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
          x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
        acctCode:
          title: Acct
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCT_CODE"
          x-lineageReferenceObject: FGBCSHD_ACCT_CODE
        criteria.drCrInd:
          title: Debit/Credit
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_DR_CR_IND"
          x-lineageReferenceObject: FGBCSHD_DR_CR_IND
        criteria.currCode:
          title: Currency
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
            reference object : gtvcurr"
          x-lineageReferenceObject: FGBCSHD_CURR_CODE
          x-lineageLookupReferenceObject: gtvcurr
        criteria.tgrpCode:
          title: Tax Group
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
            reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
          x-lineageReferenceObject: FGBCSHD_TGRP_CODE
          x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
        transDesc:
          title: Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_TRANS_DESC"
          x-lineageReferenceObject: FGBCSHD_TRANS_DESC
        abalOverride:
          title: NSF Override
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
          x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
        distPct:
          title: Percent
          maxLength: 8
          type: number
          description: "Lineage reference object : FGBCSHD_DIST_PCT"
          x-lineageReferenceObject: FGBCSHD_DIST_PCT
        criteria.orgnCode:
          title: Orgn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ORGN_CODE"
          x-lineageReferenceObject: FGBCSHD_ORGN_CODE
        criteria.bankCode:
          title: Bank
          maxLength: 30
          type: string
          description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FGBCSHD_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
      x-lineageReferenceObject: FGBCSHD
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    direct-cash-receipt-1.0.0_post_request:
      required:
        - seqNum
        - coasCode
        - transAmt
        - transDesc
        - bankCode
      type: object
      properties:
        bankCode:
          title: Bank
          maxLength: 30
          type: string
          description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
            reference object : gxvbank"
          x-lineageReferenceObject: FGBCSHD_BANK_CODE
          x-lineageLookupReferenceObject: gxvbank
        tgrpCode:
          title: Tax Group
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
            reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
          x-lineageReferenceObject: FGBCSHD_TGRP_CODE
          x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
        currCode:
          title: Currency
          maxLength: 4
          type: string
          description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
            reference object : gtvcurr"
          x-lineageReferenceObject: FGBCSHD_CURR_CODE
          x-lineageLookupReferenceObject: gtvcurr
        documentNumber:
          title: Document Number
          maxLength: 30
          type: string
          description: "Lineage reference object : documentNumber"
          x-lineageReferenceObject: documentNumber
        seqNum:
          title: Sequence
          maxLength: 4
          type: number
          description: "Lineage reference object : FGBCSHD_SEQ_NUM"
          x-lineageReferenceObject: FGBCSHD_SEQ_NUM
        acciCode:
          title: Index
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
            reference object : ftvacci"
          x-lineageReferenceObject: FGBCSHD_ACCI_CODE
          x-lineageLookupReferenceObject: ftvacci
        coasCode:
          title: COA
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
            reference object : ftvcoas"
          x-lineageReferenceObject: FGBCSHD_COAS_CODE
          x-lineageLookupReferenceObject: ftvcoas
        locnCode:
          title: Locn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_LOCN_CODE"
          x-lineageReferenceObject: FGBCSHD_LOCN_CODE
        fgbcshdAbalOverride:
          title: NSF Override
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
          x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
        orgnCode:
          title: Orgn
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ORGN_CODE"
          x-lineageReferenceObject: FGBCSHD_ORGN_CODE
        acctCode:
          title: Acct
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACCT_CODE"
          x-lineageReferenceObject: FGBCSHD_ACCT_CODE
        fundCode:
          title: Fund
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_FUND_CODE"
          x-lineageReferenceObject: FGBCSHD_FUND_CODE
        vendor:
          title: Vendor Code
          maxLength: 9
          type: string
          description: "Lineage reference object : keyBlockVendor"
          x-lineageReferenceObject: keyBlockVendor
        transDesc:
          title: Description
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_TRANS_DESC"
          x-lineageReferenceObject: FGBCSHD_TRANS_DESC
        progCode:
          title: Prog
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_PROG_CODE"
          x-lineageReferenceObject: FGBCSHD_PROG_CODE
        transAmt:
          title: Amount
          maxLength: 25
          type: number
          description: "Lineage reference object : FGBCSHD_TRANS_AMT"
          x-lineageReferenceObject: FGBCSHD_TRANS_AMT
        abalOverride:
          title: NSF Override
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
          x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
        docRefNum:
          title: Document Reference
          maxLength: 35
          type: string
          description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
          x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
        displayTaxDesc:
          maxLength: 35
          type: string
        actvCode:
          title: Actv
          maxLength: 6
          type: string
          description: "Lineage reference object : FGBCSHD_ACTV_CODE"
          x-lineageReferenceObject: FGBCSHD_ACTV_CODE
        distPct:
          title: Percent
          maxLength: 8
          type: number
          description: "Lineage reference object : FGBCSHD_DIST_PCT"
          x-lineageReferenceObject: FGBCSHD_DIST_PCT
        drCrInd:
          title: Debit/Credit
          maxLength: 1
          type: string
          description: "Lineage reference object : FGBCSHD_DR_CR_IND"
          x-lineageReferenceObject: FGBCSHD_DR_CR_IND
        depNum:
          title: Deposit
          maxLength: 8
          type: string
          description: "Lineage reference object : FGBCSHD_DEP_NUM"
          x-lineageReferenceObject: FGBCSHD_DEP_NUM
      x-lineageReferenceObject: FGBCSHD
    direct-cash-receipt-1.0.0_put_response:
      type: object
      properties:
        fgbcshh:
          type: array
          items:
            required:
              - transDate
            type: object
            properties:
              collectTaxDesc:
                maxLength: 35
                type: string
              transDate:
                title: Transaction Date
                maxLength: 26
                type: string
                description: "Lineage reference object : FGBCSHH_TRANS_DATE"
                format: date-time
                x-lineageReferenceObject: FGBCSHH_TRANS_DATE
              nsfOnOffInd:
                title: NSF Checking
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHH_NSF_ON_OFF_IND"
                x-lineageReferenceObject: FGBCSHH_NSF_ON_OFF_IND
              displayCollectTax:
                title: Collects Tax
                maxLength: 1
                type: string
              docAmt:
                title: Document Total
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHH_DOC_AMT"
                x-lineageReferenceObject: FGBCSHH_DOC_AMT
            x-lineageReferenceObject: fgbcshh
        fgbcshd:
          type: array
          items:
            required:
              - bankCode
              - coasCode
              - seqNum
              - transAmt
              - transDesc
            type: object
            properties:
              progTitle:
                maxLength: 35
                type: string
              fundTitle:
                maxLength: 35
                type: string
              currCode:
                title: Currency
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
                  reference object : gtvcurr"
                x-lineageReferenceObject: FGBCSHD_CURR_CODE
                x-lineageLookupReferenceObject: gtvcurr
              tgrpCode:
                title: Tax Group
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
                  reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
                x-lineageReferenceObject: FGBCSHD_TGRP_CODE
                x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
              coasCode:
                title: COA
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
                  reference object : ftvcoas"
                x-lineageReferenceObject: FGBCSHD_COAS_CODE
                x-lineageLookupReferenceObject: ftvcoas
              acctTitle:
                maxLength: 35
                type: string
              locnCode:
                title: Locn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_LOCN_CODE"
                x-lineageReferenceObject: FGBCSHD_LOCN_CODE
              orgnCode:
                title: Orgn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ORGN_CODE"
                x-lineageReferenceObject: FGBCSHD_ORGN_CODE
              fundCode:
                title: Fund
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_FUND_CODE"
                x-lineageReferenceObject: FGBCSHD_FUND_CODE
              actvTitle:
                maxLength: 35
                type: string
              statusInd:
                title: Status
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_STATUS_IND"
                x-lineageReferenceObject: FGBCSHD_STATUS_IND
              progCode:
                title: Prog
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_PROG_CODE"
                x-lineageReferenceObject: FGBCSHD_PROG_CODE
              transAmt:
                title: Amount
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHD_TRANS_AMT"
                x-lineageReferenceObject: FGBCSHD_TRANS_AMT
              docRefNum:
                title: Document Reference
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
                x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
              displayTaxDesc:
                maxLength: 35
                type: string
              locnTitle:
                maxLength: 35
                type: string
              actvCode:
                title: Actv
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACTV_CODE"
                x-lineageReferenceObject: FGBCSHD_ACTV_CODE
              drCrInd:
                title: Debit/Credit
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_DR_CR_IND"
                x-lineageReferenceObject: FGBCSHD_DR_CR_IND
              depNum:
                title: Deposit
                maxLength: 8
                type: string
                description: "Lineage reference object : FGBCSHD_DEP_NUM"
                x-lineageReferenceObject: FGBCSHD_DEP_NUM
              bankCode:
                title: Bank
                maxLength: 30
                type: string
                description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
                  reference object : gxvbank"
                x-lineageReferenceObject: FGBCSHD_BANK_CODE
                x-lineageLookupReferenceObject: gxvbank
              seqNum:
                title: Sequence
                maxLength: 4
                type: number
                description: "Lineage reference object : FGBCSHD_SEQ_NUM"
                x-lineageReferenceObject: FGBCSHD_SEQ_NUM
              acciCode:
                title: Index
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
                  reference object : ftvacci"
                x-lineageReferenceObject: FGBCSHD_ACCI_CODE
                x-lineageLookupReferenceObject: ftvacci
              acctCode:
                title: Acct
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCT_CODE"
                x-lineageReferenceObject: FGBCSHD_ACCT_CODE
              orgnTitle:
                maxLength: 35
                type: string
              fsyrCode:
                title: Year
                maxLength: 2
                type: string
                description: "Lineage reference object : FGBCSHD_FSYR_CODE"
                x-lineageReferenceObject: FGBCSHD_FSYR_CODE
              transDesc:
                title: Description
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_TRANS_DESC"
                x-lineageReferenceObject: FGBCSHD_TRANS_DESC
              abalOverride:
                title: NSF Override
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
                x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
              acciTitle:
                maxLength: 35
                type: string
              distPct:
                title: Percent
                maxLength: 8
                type: number
                description: "Lineage reference object : FGBCSHD_DIST_PCT"
                x-lineageReferenceObject: FGBCSHD_DIST_PCT
              coasTitle:
                maxLength: 35
                type: string
            x-lineageReferenceObject: fgbcshd
    direct-cash-receipt-1.0.0_get_request:
      type: object
      properties:
        documentNumber:
          title: Document Number
          maxLength: 30
          type: string
          description: "Lineage reference object : documentNumber"
          x-lineageReferenceObject: documentNumber
        vendor:
          title: Vendor Code
          maxLength: 9
          type: string
          description: "Lineage reference object : keyBlockVendor"
          x-lineageReferenceObject: keyBlockVendor
      x-lineageReferenceObject: KEY_BLOCK
    direct-cash-receipt-1.0.0_qapi_post:
      type: object
      properties:
        documentNumber:
          type: string
        vendor:
          type: string
    direct-cash-receipt-1.0.0_get_response:
      type: object
      properties:
        fgbcshh:
          type: array
          items:
            required:
              - transDate
            type: object
            properties:
              collectTaxDesc:
                maxLength: 35
                type: string
              transDate:
                title: Transaction Date
                maxLength: 26
                type: string
                description: "Lineage reference object : FGBCSHH_TRANS_DATE"
                format: date-time
                x-lineageReferenceObject: FGBCSHH_TRANS_DATE
              nsfOnOffInd:
                title: NSF Checking
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHH_NSF_ON_OFF_IND"
                x-lineageReferenceObject: FGBCSHH_NSF_ON_OFF_IND
              displayCollectTax:
                title: Collects Tax
                maxLength: 1
                type: string
              docAmt:
                title: Document Total
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHH_DOC_AMT"
                x-lineageReferenceObject: FGBCSHH_DOC_AMT
            x-lineageReferenceObject: fgbcshh
        form_header:
          type: array
          items:
            type: object
            properties:
              vendorNameDt:
                maxLength: 150
                type: string
                description: "Lineage reference object : vendorNameDt"
                x-lineageReferenceObject: vendorNameDt
              displayDocStatus:
                title: Document Status
                maxLength: 30
                type: string
                description: "Lineage reference object : displayDocStatus"
                x-lineageReferenceObject: displayDocStatus
              totalAmount:
                title: Total Tax
                maxLength: 31
                type: number
                description: "Lineage reference object : totalAmount"
                x-lineageReferenceObject: totalAmount
              dataSeparatorLine1:
                type: string
                description: "Lineage reference object : dataSeparatorLine1"
                x-lineageReferenceObject: dataSeparatorLine1
              convertedAmt:
                title: Convert Amount
                maxLength: 25
                type: number
                description: "Lineage reference object : convertedAmt"
                x-lineageReferenceObject: convertedAmt
              documentAmountDt:
                title: Document Total
                maxLength: 25
                type: number
                description: "Lineage reference object : documentAmountDt"
                x-lineageReferenceObject: documentAmountDt
              seqNum:
                title: Sequence
                maxLength: 4
                type: number
                description: "Lineage reference object : seqNum"
                x-lineageReferenceObject: seqNum
              dataSeparatorLine0:
                type: string
                description: "Lineage reference object : dataSeparatorLine0"
                x-lineageReferenceObject: dataSeparatorLine0
              transAmt:
                title: Transaction Amount
                maxLength: 25
                type: number
                description: "Lineage reference object : transAmt"
                x-lineageReferenceObject: transAmt
              documentNumberDt:
                title: Document Number
                maxLength: 8
                type: string
                description: "Lineage reference object : documentNumberDt"
                x-lineageReferenceObject: documentNumberDt
              vendorCodeDt:
                title: Vendor
                maxLength: 9
                type: string
                description: "Lineage reference object : vendorCodeDt"
                x-lineageReferenceObject: vendorCodeDt
              textInd:
                title: Document Text Exists
                maxLength: 1
                type: string
                description: "Lineage reference object : textInd"
                x-lineageReferenceObject: textInd
            x-lineageReferenceObject: form_header
        fgbcshd:
          type: array
          items:
            required:
              - bankCode
              - coasCode
              - seqNum
              - transAmt
              - transDesc
            type: object
            properties:
              progTitle:
                maxLength: 35
                type: string
              fundTitle:
                maxLength: 35
                type: string
              currCode:
                title: Currency
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_CURR_CODE, Lookup lineage
                  reference object : gtvcurr"
                x-lineageReferenceObject: FGBCSHD_CURR_CODE
                x-lineageLookupReferenceObject: gtvcurr
              tgrpCode:
                title: Tax Group
                maxLength: 4
                type: string
                description: "Lineage reference object : FGBCSHD_TGRP_CODE, Lookup lineage
                  reference object : ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp"
                x-lineageReferenceObject: FGBCSHD_TGRP_CODE
                x-lineageLookupReferenceObject: ftvtrat,ftvtgrp,ftrtgtr,ftvtgrp
              coasCode:
                title: COA
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_COAS_CODE, Lookup lineage
                  reference object : ftvcoas"
                x-lineageReferenceObject: FGBCSHD_COAS_CODE
                x-lineageLookupReferenceObject: ftvcoas
              acctTitle:
                maxLength: 35
                type: string
              locnCode:
                title: Locn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_LOCN_CODE"
                x-lineageReferenceObject: FGBCSHD_LOCN_CODE
              orgnCode:
                title: Orgn
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ORGN_CODE"
                x-lineageReferenceObject: FGBCSHD_ORGN_CODE
              fundCode:
                title: Fund
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_FUND_CODE"
                x-lineageReferenceObject: FGBCSHD_FUND_CODE
              actvTitle:
                maxLength: 35
                type: string
              statusInd:
                title: Status
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_STATUS_IND"
                x-lineageReferenceObject: FGBCSHD_STATUS_IND
              progCode:
                title: Prog
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_PROG_CODE"
                x-lineageReferenceObject: FGBCSHD_PROG_CODE
              transAmt:
                title: Amount
                maxLength: 25
                type: number
                description: "Lineage reference object : FGBCSHD_TRANS_AMT"
                x-lineageReferenceObject: FGBCSHD_TRANS_AMT
              docRefNum:
                title: Document Reference
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_DOC_REF_NUM"
                x-lineageReferenceObject: FGBCSHD_DOC_REF_NUM
              displayTaxDesc:
                maxLength: 35
                type: string
              locnTitle:
                maxLength: 35
                type: string
              actvCode:
                title: Actv
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACTV_CODE"
                x-lineageReferenceObject: FGBCSHD_ACTV_CODE
              drCrInd:
                title: Debit/Credit
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_DR_CR_IND"
                x-lineageReferenceObject: FGBCSHD_DR_CR_IND
              depNum:
                title: Deposit
                maxLength: 8
                type: string
                description: "Lineage reference object : FGBCSHD_DEP_NUM"
                x-lineageReferenceObject: FGBCSHD_DEP_NUM
              bankCode:
                title: Bank
                maxLength: 30
                type: string
                description: "Lineage reference object : FGBCSHD_BANK_CODE, Lookup lineage
                  reference object : gxvbank"
                x-lineageReferenceObject: FGBCSHD_BANK_CODE
                x-lineageLookupReferenceObject: gxvbank
              seqNum:
                title: Sequence
                maxLength: 4
                type: number
                description: "Lineage reference object : FGBCSHD_SEQ_NUM"
                x-lineageReferenceObject: FGBCSHD_SEQ_NUM
              acciCode:
                title: Index
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCI_CODE, Lookup lineage
                  reference object : ftvacci"
                x-lineageReferenceObject: FGBCSHD_ACCI_CODE
                x-lineageLookupReferenceObject: ftvacci
              acctCode:
                title: Acct
                maxLength: 6
                type: string
                description: "Lineage reference object : FGBCSHD_ACCT_CODE"
                x-lineageReferenceObject: FGBCSHD_ACCT_CODE
              orgnTitle:
                maxLength: 35
                type: string
              fsyrCode:
                title: Year
                maxLength: 2
                type: string
                description: "Lineage reference object : FGBCSHD_FSYR_CODE"
                x-lineageReferenceObject: FGBCSHD_FSYR_CODE
              transDesc:
                title: Description
                maxLength: 35
                type: string
                description: "Lineage reference object : FGBCSHD_TRANS_DESC"
                x-lineageReferenceObject: FGBCSHD_TRANS_DESC
              abalOverride:
                title: NSF Override
                maxLength: 1
                type: string
                description: "Lineage reference object : FGBCSHD_ABAL_OVERRIDE"
                x-lineageReferenceObject: FGBCSHD_ABAL_OVERRIDE
              acciTitle:
                maxLength: 35
                type: string
              distPct:
                title: Percent
                maxLength: 8
                type: number
                description: "Lineage reference object : FGBCSHD_DIST_PCT"
                x-lineageReferenceObject: FGBCSHD_DIST_PCT
              coasTitle:
                maxLength: 35
                type: string
            x-lineageReferenceObject: fgbcshd
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
