openapi: 3.0.0
info:
  title: hdr-scholarship
  description: API for SOAHDRE administrative page
  version: 1.0.0
  x-source-name: SOAHDRE
  x-source-title: Higher Degree Research
  x-source-system: banner
  x-api-type: bus-poc
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/hdr-scholarship:
    get:
      tags:
        - hdr-scholarship
      summary: Return resources from SOAHDRE
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma separated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: keyStudypath
          in: query
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          description: Term
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHSCO_TERM_CODE
        - name: hdrSchlshipTypeCde
          in: query
          description: Scholarship Type
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
        - name: effectiveFromDate
          in: query
          description: Effective From Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        - name: effectiveToDate
          in: query
          description: Effective To Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        - name: activeInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/hdr-scholarship-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - hdr-scholarship
      summary: Updates an existing resource in SOAHDRE
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/hdr-scholarship-1.0.0_put_request"
            example:
              activeInd: N
              effectiveToDate: 2023-06-25
              hdrSchlshipTypeCde: 10
              id: Q00050587
              keyStudypath: 1
              effectiveFromDate: 2023-02-18
              criteria.termCode: 202311
              termCode: 202331
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/hdr-scholarship-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - hdr-scholarship
      summary: Creates a new resource in SOAHDRE
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/hdr-scholarship-1.0.0_post_request"
            example:
              activeInd: N
              effectiveToDate: 2024-05-15
              hdrSchlshipTypeCde: 10
              id: Q00050587
              keyStudypath: 1
              effectiveFromDate: 2024-01-30
              termCode: 202311
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/hdr-scholarship-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/hdr-scholarship:
    post:
      tags:
        - hdr-scholarship QAPI (Query by POST)
      summary: Return resources from SOAHDRE
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/hdr-scholarship-1.0.0_qapi_post_request"
            example:
              id: Q00050587
              keyStudypath: 1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/hdr-scholarship-1.0.0_qapi_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    hdr-scholarship-1.0.0_qapi_post_response:
      required:
        - effectiveFromDate
        - hdrSchlshipTypeCde
        - termCode
      type: object
      properties:
        activityDate:
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_ACTIVITY_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        scholarshipTypeDesc:
          type: string
        userId:
          type: string
          description: "Lineage reference object : SORHSCO_USER_ID"
          x-lineageReferenceObject: SORHSCO_USER_ID
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhsco
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    hdr-scholarship-1.0.0_qapi_post_request:
      required:
        - termCode
        - hdrSchlshipTypeCde
        - effectiveFromDate
      type: object
      properties:
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SORHSCO
    hdr-scholarship-1.0.0_post_response:
      required:
        - effectiveFromDate
        - hdrSchlshipTypeCde
        - termCode
      type: object
      properties:
        activityDate:
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_ACTIVITY_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        scholarshipTypeDesc:
          type: string
        userId:
          type: string
          description: "Lineage reference object : SORHSCO_USER_ID"
          x-lineageReferenceObject: SORHSCO_USER_ID
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhsco
    hdr-scholarship-1.0.0_put_request:
      required:
        - criteria.termCode
        - criteria.hdrSchlshipTypeCde
        - criteria.effectiveFromDate
        - termCode
        - hdrSchlshipTypeCde
        - effectiveFromDate
      type: object
      properties:
        criteria.effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        criteria.effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        criteria.termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        criteria.hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SORHSCO
    hdr-scholarship-1.0.0_put_response:
      required:
        - effectiveFromDate
        - hdrSchlshipTypeCde
        - termCode
      type: object
      properties:
        activityDate:
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_ACTIVITY_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        scholarshipTypeDesc:
          type: string
        userId:
          type: string
          description: "Lineage reference object : SORHSCO_USER_ID"
          x-lineageReferenceObject: SORHSCO_USER_ID
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhsco
    hdr-scholarship-1.0.0_post_request:
      required:
        - termCode
        - hdrSchlshipTypeCde
        - effectiveFromDate
      type: object
      properties:
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: SORHSCO
    hdr-scholarship-1.0.0_get_response:
      required:
        - effectiveFromDate
        - hdrSchlshipTypeCde
        - termCode
      type: object
      properties:
        activityDate:
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_ACTIVITY_DATE
        activeInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : SORHSCO_ACTIVE_IND"
          x-lineageReferenceObject: SORHSCO_ACTIVE_IND
        effectiveToDate:
          title: Effective To Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_TO_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_TO_DATE
        hdrSchlshipTypeCde:
          title: Scholarship Type
          maxLength: 2
          type: string
          description: "Lineage reference object : SORHSCO_HDR_SCHLSHIP_TYPE_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHSCO_HDR_SCHLSHIP_TYPE_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        effectiveFromDate:
          title: Effective From Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHSCO_EFFECTIVE_FROM_DATE"
          format: date-time
          x-lineageReferenceObject: SORHSCO_EFFECTIVE_FROM_DATE
        scholarshipTypeDesc:
          type: string
        userId:
          type: string
          description: "Lineage reference object : SORHSCO_USER_ID"
          x-lineageReferenceObject: SORHSCO_USER_ID
        termCode:
          title: Term
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHSCO_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHSCO_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhsco
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
