openapi: 3.0.0
info:
  title: higher-degree-research-details
  description: API for SOAHDRE administrative page
  version: 1.0.0
  x-source-name: SOAHDRE
  x-source-title: Higher Degree Research
  x-source-system: banner
  x-api-type: bus-poc
  x-release-status: ga
  x-source-domain: Student
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/higher-degree-research-details:
    get:
      tags:
        - higher-degree-research-details
      summary: Return resources from SOAHDRE
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma separated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: keyStudypath
          in: query
          required: false
          schema:
            type: string
        - name: termCode
          in: query
          description: Sorhdre Term Code
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_TERM_CODE
        - name: primeResearchCde
          in: query
          description: Sorhdre Prime Research Cde
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
        - name: secndResearchCde
          in: query
          description: Sorhdre Secnd Research Cde
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
        - name: hdrThesisSubDate
          in: query
          description: Sorhdre Hdr Thesis Sub Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        - name: activityDate
          in: query
          description: Sorhdre Activity Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        - name: userId
          in: query
          description: Sorhdre User Id
          required: false
          schema:
            type: string
          x-lineageReferenceObject: SORHDRE_USER_ID
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/higher-degree-research-details-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - higher-degree-research-details
      summary: Updates an existing resource in SOAHDRE
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/higher-degree-research-details-1.0.0_put_request"
            example:
              secndResearchCde: 5002
              id: Q00050587
              keyStudypath: 1
              hdrThesisSubDate: 2023-03-21
              criteria.termCode: 202311
              termCode: 202331
              primeResearchCde: 5002
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/higher-degree-research-details-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - higher-degree-research-details
      summary: Creates a new resource in SOAHDRE
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/higher-degree-research-details-1.0.0_post_request"
            example:
              secndResearchCde: 5002
              id: Q00050587
              keyStudypath: 1
              hdrThesisSubDate: 2023-03-21
              termCode: 202311
              primeResearchCde: 5002
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/higher-degree-research-details-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/higher-degree-research-details:
    post:
      tags:
        - higher-degree-research-details QAPI (Query by POST)
      summary: Return resources from SOAHDRE
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/higher-degree-research-details-1.0.0_qapi_post_requ\
                est"
            example:
              id: Q00050587
              keyStudypath: 1
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/higher-degree-research-details-1.0.0_qapi_post_resp\
                    onse"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    higher-degree-research-details-1.0.0_qapi_post_response:
      required:
        - termCode
      type: object
      properties:
        secndResearchDesc:
          type: string
        activityDate:
          title: Sorhdre Activity Date
          type: string
          description: "Lineage reference object : SORHDRE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        primeResearchDesc:
          type: string
        userId:
          title: Sorhdre User Id
          type: string
          description: "Lineage reference object : SORHDRE_USER_ID"
          x-lineageReferenceObject: SORHDRE_USER_ID
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhdre
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The global identifier of the resource in error.
              sourceId:
                type: string
                description: The source applications data reference identifier for the primary
                  data entity used to create the resource. This is useful for
                  referencing the source item through the applications
                  administrative user interface.
              code:
                type: string
                description: The error message code used to describe the error details.
              description:
                type: string
                description: The error description used to describe the error details.
              message:
                type: string
                description: "The detailed actionable error message. "
    higher-degree-research-details-1.0.0_put_request:
      required:
        - criteria.termCode
        - termCode
      type: object
      properties:
        criteria.primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        criteria.hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        criteria.termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        criteria.secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
      x-lineageReferenceObject: SORHDRE
    higher-degree-research-details-1.0.0_qapi_post_request:
      required:
        - termCode
      type: object
      properties:
        activityDate:
          title: Sorhdre Activity Date
          type: string
          description: "Lineage reference object : SORHDRE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        userId:
          title: Sorhdre User Id
          type: string
          description: "Lineage reference object : SORHDRE_USER_ID"
          x-lineageReferenceObject: SORHDRE_USER_ID
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
      x-lineageReferenceObject: SORHDRE
    higher-degree-research-details-1.0.0_post_request:
      required:
        - termCode
      type: object
      properties:
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyStudypath:
          title: Study Path
          maxLength: 2
          type: number
          description: "Lineage reference object : keyStudypath, Lookup lineage reference
            object :
            sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgr\
            stsp,sovlcur"
          x-lineageReferenceObject: keyStudypath
          x-lineageLookupReferenceObject: sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
      x-lineageReferenceObject: SORHDRE
    higher-degree-research-details-1.0.0_put_response:
      required:
        - termCode
      type: object
      properties:
        secndResearchDesc:
          type: string
        activityDate:
          title: Sorhdre Activity Date
          type: string
          description: "Lineage reference object : SORHDRE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        primeResearchDesc:
          type: string
        userId:
          title: Sorhdre User Id
          type: string
          description: "Lineage reference object : SORHDRE_USER_ID"
          x-lineageReferenceObject: SORHDRE_USER_ID
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhdre
    higher-degree-research-details-1.0.0_get_response:
      required:
        - termCode
      type: object
      properties:
        secndResearchDesc:
          type: string
        activityDate:
          title: Sorhdre Activity Date
          type: string
          description: "Lineage reference object : SORHDRE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        primeResearchDesc:
          type: string
        userId:
          title: Sorhdre User Id
          type: string
          description: "Lineage reference object : SORHDRE_USER_ID"
          x-lineageReferenceObject: SORHDRE_USER_ID
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhdre
    higher-degree-research-details-1.0.0_post_response:
      required:
        - termCode
      type: object
      properties:
        secndResearchDesc:
          type: string
        activityDate:
          title: Sorhdre Activity Date
          type: string
          description: "Lineage reference object : SORHDRE_ACTIVITY_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_ACTIVITY_DATE
        secndResearchCde:
          title: Sorhdre Secnd Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_SECND_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_SECND_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        hdrThesisSubDate:
          title: Sorhdre Hdr Thesis Sub Date
          maxLength: 11
          type: string
          description: "Lineage reference object : SORHDRE_HDR_THESIS_SUB_DATE"
          format: date-time
          x-lineageReferenceObject: SORHDRE_HDR_THESIS_SUB_DATE
        primeResearchDesc:
          type: string
        userId:
          title: Sorhdre User Id
          type: string
          description: "Lineage reference object : SORHDRE_USER_ID"
          x-lineageReferenceObject: SORHDRE_USER_ID
        primeResearchCde:
          title: Sorhdre Prime Research Cde
          maxLength: 4
          type: string
          description: "Lineage reference object : SORHDRE_PRIME_RESEARCH_CDE, Lookup
            lineage reference object : SKRRVAL"
          x-lineageReferenceObject: SORHDRE_PRIME_RESEARCH_CDE
          x-lineageLookupReferenceObject: SKRRVAL
        termCode:
          title: Sorhdre Term Code
          maxLength: 6
          type: string
          description: "Lineage reference object : SORHDRE_TERM_CODE, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: SORHDRE_TERM_CODE
          x-lineageLookupReferenceObject: stvterm
      x-lineageReferenceObject: sorhdre
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
