openapi: 3.0.0
info:
  title: applicant-mail
  description: API for RUAMAIL administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: beta
  x-source-name: RUAMAIL
  x-source-domain: Financial Aid
  x-source-title: Applicant Mail
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/applicant-mail:
    get:
      tags:
        - applicant-mail
      summary: Return resources from RUAMAIL
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: keyblckAidyCode
          in: query
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: systemInd
          in: query
          description: System
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        - name: aidyCode
          in: query
          description: Aid Year
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
        - name: moduleCode
          in: query
          description: Module
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        - name: letrCode
          in: query
          description: Letter
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_LETR_CODE
        - name: description
          in: query
          required: false
          schema:
            type: string
        - name: dateInit
          in: query
          description: Initiated
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        - name: datePrinted
          in: query
          description: Print Date
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        - name: waitDays
          in: query
          description: Wait
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        - name: origInd
          in: query
          description: Originator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        - name: user
          in: query
          description: User ID
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_USER
        - name: initCode
          in: query
          description: Initials
          required: false
          schema:
            type: string
          x-lineageReferenceObject: GURMAIL_INIT_CODE
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-mail-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    put:
      tags:
        - applicant-mail
      summary: Updates an existing resource in RUAMAIL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-mail-1.0.0_put_request"
            example:
              dateInit: 2020-06-07
              letrCode: ADM_APPL_ACKN
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-mail-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
        - applicant-mail
      summary: Creates a new resource in RUAMAIL
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-mail-1.0.0_post_request"
            example:
              letrCode: ADM_CHKL
              id: A00030988
              keyblckAidyCode: 2122
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-mail-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /qapi/applicant-mail:
    post:
      tags:
        - applicant-mail QAPI (Query by POST)
      summary: Return resources from RUAMAIL
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/applicant-mail-1.0.0_get_request"
            example:
              keyblckAidyCode: 2122
              id: A00030988
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/applicant-mail-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    applicant-mail-1.0.0_put_response:
      required:
        - aidyCode
        - letrCode
        - systemInd
      type: object
      properties:
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
          x-lineageLookupReferenceObject: robinst
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        description:
          type: string
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        origInd:
          title: Originator
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_ORIG_IND"
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        user:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_USER"
          x-lineageReferenceObject: GURMAIL_USER
      x-lineageReferenceObject: gurmail
    applicant-mail-1.0.0_post_request:
      required:
        - keyblckAidyCode
        - id
        - letrCode
      type: object
      properties:
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        keyblckAidyCode:
                title: Aid Year
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblckAidyCode, Lookup lineage
                  reference object : robinst"
                x-lineageReferenceObject: keyblckAidyCode
                x-lineageLookupReferenceObject: robinst 
        systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
      x-lineageReferenceObject: GURMAIL
    applicant-mail-1.0.0_post_response:
      required:
        - keyblckAidyCode
        - letrCode
        - systemInd
      type: object
      properties:
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
          x-lineageLookupReferenceObject: robinst
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        description:
          type: string
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        origInd:
          title: Originator
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_ORIG_IND"
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        user:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_USER"
          x-lineageReferenceObject: GURMAIL_USER
      x-lineageReferenceObject: gurmail
    applicant-mail-1.0.0_get_response:
      type: object
      properties:
        key_block:
          type: array
          items:
            type: object
            properties:
              keyblckAidyCode:
                title: Aid Year
                maxLength: 30
                type: string
                description: "Lineage reference object : keyblckAidyCode, Lookup lineage
                  reference object : robinst"
                x-lineageReferenceObject: keyblckAidyCode
                x-lineageLookupReferenceObject: robinst
              displayMessage:
                maxLength: 30
                type: string
                description: "Lineage reference object : displayMessage"
                x-lineageReferenceObject: displayMessage
              statAwdLtrInd:
                title: Award Letter
                maxLength: 1
                type: string
                description: "Lineage reference object : statAwdLtrInd"
                x-lineageReferenceObject: statAwdLtrInd
              rwname:
                maxLength: 230
                type: string
                description: "Lineage reference object : rwname"
                x-lineageReferenceObject: rwname
              id:
                title: ID
                maxLength: 9
                type: string
                description: "Lineage reference object : id"
                x-lineageReferenceObject: id
              confidInfo:
                maxLength: 16
                type: string
                description: "Lineage reference object : confidInfo"
                x-lineageReferenceObject: confidInfo
              deceasedInd:
                maxLength: 12
                type: string
                description: "Lineage reference object : deceasedInd"
                x-lineageReferenceObject: deceasedInd
            x-lineageReferenceObject: key_block
        gurmail:
          type: array
          items:
            required:
              - aidyCode
              - letrCode
              - systemInd
            type: object
            properties:
              moduleCode:
                title: Module
                maxLength: 1
                type: string
                description: "Lineage reference object : GURMAIL_MODULE_CODE"
                x-lineageReferenceObject: GURMAIL_MODULE_CODE
              aidyCode:
                title: Aid Year
                maxLength: 30
                type: string
                description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
                  reference object : robinst"
                x-lineageReferenceObject: GURMAIL_AIDY_CODE
                x-lineageLookupReferenceObject: robinst
              waitDays:
                title: Wait
                maxLength: 3
                type: number
                description: "Lineage reference object : GURMAIL_WAIT_DAYS"
                x-lineageReferenceObject: GURMAIL_WAIT_DAYS
              initCode:
                title: Initials
                maxLength: 30
                type: string
                description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
                  reference object : stvinit"
                x-lineageReferenceObject: GURMAIL_INIT_CODE
                x-lineageLookupReferenceObject: stvinit
              datePrinted:
                title: Print Date
                maxLength: 11
                type: string
                description: "Lineage reference object : GURMAIL_DATE_PRINTED"
                format: date
                x-lineageReferenceObject: GURMAIL_DATE_PRINTED
              dateInit:
                title: Initiated
                maxLength: 11
                type: string
                description: "Lineage reference object : GURMAIL_DATE_INIT"
                format: date
                x-lineageReferenceObject: GURMAIL_DATE_INIT
              description:
                type: string
              letrCode:
                title: Letter
                maxLength: 30
                type: string
                description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
                  reference object : gtvletr"
                x-lineageReferenceObject: GURMAIL_LETR_CODE
                x-lineageLookupReferenceObject: gtvletr
              systemInd:
                title: System
                maxLength: 30
                type: string
                description: "Lineage reference object : GURMAIL_SYSTEM_IND"
                x-lineageReferenceObject: GURMAIL_SYSTEM_IND
              origInd:
                title: Originator
                maxLength: 1
                type: string
                description: "Lineage reference object : GURMAIL_ORIG_IND"
                x-lineageReferenceObject: GURMAIL_ORIG_IND
              user:
                title: User ID
                maxLength: 30
                type: string
                description: "Lineage reference object : GURMAIL_USER"
                x-lineageReferenceObject: GURMAIL_USER
            x-lineageReferenceObject: gurmail
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    applicant-mail-1.0.0_put_request:
      required:
        - criteria.systemInd
        - criteria.aidyCode
        - criteria.letrCode
        - letrCode
      type: object
      properties:
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        criteria.datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        criteria.description:
          type: string
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        criteria.systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        criteria.waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        criteria.user:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_USER"
          x-lineageReferenceObject: GURMAIL_USER
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        criteria.aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
          x-lineageLookupReferenceObject: robinst
        criteria.origInd:
          title: Originator
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_ORIG_IND"
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        criteria.letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        criteria.dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        criteria.initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        criteria.moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
      x-lineageReferenceObject: GURMAIL
    applicant-mail-1.0.0_get_request:
      required:
        - systemInd
        - id
        - letrCode
      type: object
      properties:
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
          x-lineageLookupReferenceObject: robinst
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        description:
          type: string
        origInd:
          title: Originator
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_ORIG_IND"
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        keyblckAidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblckAidyCode, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: keyblckAidyCode
          x-lineageLookupReferenceObject: robinst
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        id:
          title: ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        user:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_USER"
          x-lineageReferenceObject: GURMAIL_USER
      x-lineageReferenceObject: GURMAIL
    applicant-mail-1.0.0_qapi_post:
      type: object
      properties:
        keyblckAidyCode:
          type: string
        id:
          type: string
        systemInd:
          title: System
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_SYSTEM_IND"
          x-lineageReferenceObject: GURMAIL_SYSTEM_IND
        aidyCode:
          title: Aid Year
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_AIDY_CODE, Lookup lineage
            reference object : robinst"
          x-lineageReferenceObject: GURMAIL_AIDY_CODE
          x-lineageLookupReferenceObject: robinst
        moduleCode:
          title: Module
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_MODULE_CODE"
          x-lineageReferenceObject: GURMAIL_MODULE_CODE
        letrCode:
          title: Letter
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_LETR_CODE, Lookup lineage
            reference object : gtvletr"
          x-lineageReferenceObject: GURMAIL_LETR_CODE
          x-lineageLookupReferenceObject: gtvletr
        description:
          type: string
        dateInit:
          title: Initiated
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_INIT"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_INIT
        datePrinted:
          title: Print Date
          maxLength: 11
          type: string
          description: "Lineage reference object : GURMAIL_DATE_PRINTED"
          format: date
          x-lineageReferenceObject: GURMAIL_DATE_PRINTED
        waitDays:
          title: Wait
          maxLength: 3
          type: number
          description: "Lineage reference object : GURMAIL_WAIT_DAYS"
          x-lineageReferenceObject: GURMAIL_WAIT_DAYS
        origInd:
          title: Originator
          maxLength: 1
          type: string
          description: "Lineage reference object : GURMAIL_ORIG_IND"
          x-lineageReferenceObject: GURMAIL_ORIG_IND
        user:
          title: User ID
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_USER"
          x-lineageReferenceObject: GURMAIL_USER
        initCode:
          title: Initials
          maxLength: 30
          type: string
          description: "Lineage reference object : GURMAIL_INIT_CODE, Lookup lineage
            reference object : stvinit"
          x-lineageReferenceObject: GURMAIL_INIT_CODE
          x-lineageLookupReferenceObject: stvinit
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer