openapi: 3.0.0
info:
  title: exemption-authorization-category-code-level-authorization
  description: API for TSAEXPT, Category Code Level Authorization administrative page.
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TSAEXPT
  x-source-domain: Student
  x-source-title: Exemption Authorization
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/exemption-authorization-category-code-level-authorization:
    get:
      tags:
        - exemption-authorization-category-code-level-authorization
      summary: Return resources from TSAEXPT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: exemptionCode
          in: query
          required: false
          schema:
            type: string
        - name: keyblocTermCode
          in: query
          required: false
          schema:
            type: string
        - name: desc
          in: query
          required: false
          schema:
            type: string
        - name: dcatCode
          in: query
          description: Category
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_DCAT_CODE
        - name: ttvdcatDesc
          in: query
          description: Description
          required: false
          schema:
            type: string
        - name: dcatPriority
          in: query
          description: Priority
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
        - name: percent
          in: query
          description: Percent
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_PERCENT
        - name: minAmount
          in: query
          description: Minimum Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
        - name: maxAmount
          in: query
          description: Maximum Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
        - name: iESourceInd
          in: query
          description: Source Indicator
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/exemption-authorization-category-code-level-authori\
                    zation-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
    post:
      tags:
      - exemption-authorization-category-code-level-authorization
      summary: Creates a new resource in TSAEXPT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/exemption-authorization-category-code-level-authorization-1.0.0_post_request'
            example:
              exemptionCode: "1"
              keyblocTermCode: "201210"
              dcatCode: "BIL" 
              dcatPriority: "2"
              percent: "50"
              minAmount: "1"
              maxAmount: "100"
              iESourceInd: "E"
              sourceCode: "A"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/exemption-authorization-category-code-level-authorization-1.0.0_post_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
    put:
      tags:
      - exemption-authorization-category-code-level-authorization
      summary: Updates an existing resource in TSAEXPT
      parameters: []
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: '#/components/schemas/exemption-authorization-category-code-level-authorization-1.0.0_put_request'
            example:
              exemptionCode: "1"
              keyblocTermCode: "201210"
              criteria.dcatCode: "ABC"
              criteria.dcatPriority: "2"
              percent: "12" 
              minAmount: "1"
              iESourceInd: "E"
              sourceCode: "A"
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: "If STP (MEP) is enabled, returns the MEP code the response\
                \ body is associated to"
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/exemption-authorization-category-code-level-authorization-1.0.0_put_response'
        "401":
          description: Failure. Unauthorized
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
      security:
      - BasicAuth: []
  /qapi/exemption-authorization-category-code-level-authorization:
    post:
      tags:
        - exemption-authorization-category-code-level-authorization QAPI (Query
          by POST)
      summary: Return resources from TSAEXPT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/exemption-authorization-category-code-level-authori\
                zation-1.0.0_get_request"
            example:
              exemptionCode: 1
              keyblocTermCode: 199510
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/exemption-authorization-category-code-level-authori\
                    zation-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    exemption-authorization-category-code-level-authorization-1.0.0_get_request:
      required:
        - desc
        - dcatCode
        - dcatPriority
        - percent
        - iESourceInd
      type: object
      properties:
        exemptionCode:
          title: Exemption Code
          maxLength: 8
          type: string
          description: "Lineage reference object : exemptionCode"
          x-lineageReferenceObject: exemptionCode
        minAmount:
          title: Minimum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRECAT_MIN_AMOUNT"
          x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
        ttvdcatDesc:
          title: Description
          type: string
        keyblocTermCode:
          title: Term
          maxLength: 30
          type: string
          description: "Lineage reference object : keyblocTermCode, Lookup lineage
            reference object : stvterm"
          x-lineageReferenceObject: keyblocTermCode
          x-lineageLookupReferenceObject: stvterm
        iESourceInd:
          title: Source Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRECAT_I_E_SOURCE_IND"
          x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
        dcatCode:
          title: Category
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRECAT_DCAT_CODE, Lookup lineage
            reference object : ttvdcat"
          x-lineageReferenceObject: TBRECAT_DCAT_CODE
          x-lineageLookupReferenceObject: ttvdcat
        dcatPriority:
          title: Priority
          maxLength: 3
          type: number
          description: "Lineage reference object : TBRECAT_DCAT_PRIORITY"
          x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
        maxAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRECAT_MAX_AMOUNT"
          x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
        percent:
          title: Percent
          maxLength: 3
          type: number
          description: "Lineage reference object : TBRECAT_PERCENT"
          x-lineageReferenceObject: TBRECAT_PERCENT
        desc:
          title: Description
          maxLength: 30
          type: string
          description: "Lineage reference object : TBBEXPT_DESC"
          x-lineageReferenceObject: TBBEXPT_DESC
      x-lineageReferenceObject: TBRECAT
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    exemption-authorization-category-code-level-authorization-1.0.0_qapi_post:
      type: object
      properties:
        exemptionCode:
          type: string
        keyblocTermCode:
          type: string
        desc:
          type: string
        dcatCode:
          title: Category
          maxLength: 30
          type: string
          description: "Lineage reference object : TBRECAT_DCAT_CODE, Lookup lineage
            reference object : ttvdcat"
          x-lineageReferenceObject: TBRECAT_DCAT_CODE
          x-lineageLookupReferenceObject: ttvdcat
        ttvdcatDesc:
          title: Description
          type: string
        dcatPriority:
          title: Priority
          maxLength: 3
          type: number
          description: "Lineage reference object : TBRECAT_DCAT_PRIORITY"
          x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
        percent:
          title: Percent
          maxLength: 3
          type: number
          description: "Lineage reference object : TBRECAT_PERCENT"
          x-lineageReferenceObject: TBRECAT_PERCENT
        minAmount:
          title: Minimum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRECAT_MIN_AMOUNT"
          x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
        maxAmount:
          title: Maximum Amount
          maxLength: 9
          type: number
          description: "Lineage reference object : TBRECAT_MAX_AMOUNT"
          x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
        iESourceInd:
          title: Source Indicator
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRECAT_I_E_SOURCE_IND"
          x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
    exemption-authorization-category-code-level-authorization-1.0.0_get_response:
      type: object
      properties:
        tbbexpt:
          type: array
          items:
            required:
              - desc
              - detailCode
            type: object
            properties:
              detailDesc:
                type: string
              studentExptRollInd:
                title: Roll Students
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBEXPT_STUDENT_EXPT_ROLL_IND"
                x-lineageReferenceObject: TBBEXPT_STUDENT_EXPT_ROLL_IND
              termCodeExpiration:
                title: Roll Expiration Term
                maxLength: 30
                type: string
                description: "Lineage reference object : TBBEXPT_TERM_CODE_EXPIRATION, Lookup
                  lineage reference object : stvterm"
                x-lineageReferenceObject: TBBEXPT_TERM_CODE_EXPIRATION
                x-lineageLookupReferenceObject: stvterm
              expTermCodeDesc:
                type: string
              exemptionRollInd:
                title: Roll Exemptions
                maxLength: 1
                type: string
                description: "Lineage reference object : TBBEXPT_EXEMPTION_ROLL_IND"
                x-lineageReferenceObject: TBBEXPT_EXEMPTION_ROLL_IND
              detailCode:
                title: Detail Payment Code
                maxLength: 30
                type: string
                description: "Lineage reference object : TBBEXPT_DETAIL_CODE, Lookup lineage
                  reference object : tbbdetc"
                x-lineageReferenceObject: TBBEXPT_DETAIL_CODE
                x-lineageLookupReferenceObject: tbbdetc
              desc:
                title: Description
                maxLength: 30
                type: string
                description: "Lineage reference object : TBBEXPT_DESC"
                x-lineageReferenceObject: TBBEXPT_DESC
            x-lineageReferenceObject: tbbexpt
        tbrecat:
          type: array
          items:
            required:
              - dcatCode
              - dcatPriority
              - iESourceInd
              - percent
            type: object
            properties:
              minAmount:
                title: Minimum Amount
                maxLength: 9
                type: number
                description: "Lineage reference object : TBRECAT_MIN_AMOUNT"
                x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
              ttvdcatDesc:
                title: Description
                type: string
              iESourceInd:
                title: Source Indicator
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRECAT_I_E_SOURCE_IND"
                x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
              dcatCode:
                title: Category
                maxLength: 30
                type: string
                description: "Lineage reference object : TBRECAT_DCAT_CODE, Lookup lineage
                  reference object : ttvdcat"
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
                x-lineageLookupReferenceObject: ttvdcat
              dcatPriority:
                title: Priority
                maxLength: 3
                type: number
                description: "Lineage reference object : TBRECAT_DCAT_PRIORITY"
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              maxAmount:
                title: Maximum Amount
                maxLength: 9
                type: number
                description: "Lineage reference object : TBRECAT_MAX_AMOUNT"
                x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
              percent:
                title: Percent
                maxLength: 3
                type: number
                description: "Lineage reference object : TBRECAT_PERCENT"
                x-lineageReferenceObject: TBRECAT_PERCENT
            x-lineageReferenceObject: tbrecat
    exemption-authorization-category-code-level-authorization-1.0.0_post_response:
      type: object
      properties:
        tbrccat:
          type: array
          items:
            required:
            - dcatCode
            - dcatPriority
            - iESourceInd
            - percent
            type: object
            properties:
              dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              percent:
                title: Percent
                maxLength: 3
                type: number
                description: "This field identifies the percentage of the charge associated with the detail category code that the third party Exemption will cover."
                x-lineageReferenceObject: TBRECAT_PERCENT
              minAmount:
                title: Minimum Amount
                type: number
                description: "This field indicates the minimum amount the student must pay for the charge associated with the detail category code, that the third party will not cover."
                x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
              maxAmount:
                title: Maximum Amount
                type: number
                description: "This field indicates the maximum amount the third party Exemption will cover of the detail category code."
                x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
              iESourceInd:
                title: Include Exclude Indicator
                type: string
                description: "Indicator telling whether the source codes in TBRECSI should be included or excluded. Value of Null indicates that all sources in TTVSRCE are included."
                x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
            x-lineageReferenceObject: tbrccat
        tbrecsi:
          type: array
          items:
            required:
            - sourceCode
            type: object
            properties:
              sourceCode:
                title: Source
                maxLength: 30
                type: string
                description: "This field contains the source code which will be paid by the Exemption."
                x-lineageReferenceObject: TBRECSI_SOURCE_CODE
            x-lineageReferenceObject: tbrecsi
    exemption-authorization-category-code-level-authorization-1.0.0_post_request:
      required:
      - dcatCode
      - dcatPriority
      - percent
      - iESourceInd
      - sourceCode
      type: object
      properties:
        tbrccat:
          type: array
          items:
            required:
            - dcatCode
            - dcatPriority
            - iESourceInd
            - percent
            type: object
            properties:
              dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              percent:
                title: Percent
                maxLength: 3
                type: number
                description: "This field identifies the percentage of the charge associated with the detail category code that the third party Exemption will cover."
                x-lineageReferenceObject: TBRECAT_PERCENT
              minAmount:
                title: Minimum Amount
                type: number
                description: "This field indicates the minimum amount the student must pay for the charge associated with the detail category code, that the third party will not cover."
                x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
              maxAmount:
                title: Maximum Amount
                type: number
                description: "This field indicates the maximum amount the third party Exemption will cover of the detail category code."
                x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
              iESourceInd:
                title: Include Exclude Indicator
                type: string
                description: "Indicator telling whether the source codes in TBRECSI should be included or excluded. Value of Null indicates that all sources in TTVSRCE are included."
                x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
            x-lineageReferenceObject: tbrccat
        tbrecsi:
          type: array
          items:
            required:
            - sourceCode
            type: object
            properties:
              sourceCode:
                title: Source
                maxLength: 30
                type: string
                description: "This field contains the source code which will be paid by the Exemption."
                x-lineageReferenceObject: TBRECSI_SOURCE_CODE
            x-lineageReferenceObject: tbrecsi
    exemption-authorization-category-code-level-authorization-1.0.0_put_request:
      required:
      - criteria.dcatCode
      - criteria.dcatPriority
      type: object
      properties:
        tbrccat:
          type: array
          items:
            required:
            - dcatCode
            - dcatPriority
            - iESourceInd
            - percent
            type: object
            properties:
              criteria.dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              criteria.dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              percent:
                title: Percent
                maxLength: 3
                type: number
                description: "This field identifies the percentage of the charge associated with the detail category code that the third party Exemption will cover."
                x-lineageReferenceObject: TBRECAT_PERCENT
              minAmount:
                title: Minimum Amount
                type: number
                description: "This field indicates the minimum amount the student must pay for the charge associated with the detail category code, that the third party will not cover."
                x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
              maxAmount:
                title: Maximum Amount
                type: number
                description: "This field indicates the maximum amount the third party Exemption will cover of the detail category code."
                x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
              iESourceInd:
                title: Include Exclude Indicator
                type: string
                description: "Indicator telling whether the source codes in TBRECSI should be included or excluded. Value of Null indicates that all sources in TTVSRCE are included."
                x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
            x-lineageReferenceObject: tbrccat
        tbrecsi:
          type: array
          items:
            required:
            - sourceCode
            type: object
            properties:
              sourceCode:
                title: Source
                maxLength: 30
                type: string
                description: "This field contains the source code which will be paid by the Exemption."
                x-lineageReferenceObject: TBRECSI_SOURCE_CODE
            x-lineageReferenceObject: tbrecsi
    exemption-authorization-category-code-level-authorization-1.0.0_put_response:
      type: object
      properties:
        tbrccat:
          type: array
          items:
            required:
            - dcatCode
            - dcatPriority
            - iESourceInd
            - percent
            type: object
            properties:
              criteria.dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              criteria.dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              dcatCode:
                title: Detail Category Code
                type: string
                description: "This field identifies the detail category code that the third party Exemption will apply to."
                x-lineageReferenceObject: TBRECAT_DCAT_CODE
              dcatPriority:
                title: Category Code Priority
                type: number
                description: "This indicates the priority of this category code for exemption payment calculation for a student. Used only when student maximum is applied."
                x-lineageReferenceObject: TBRECAT_DCAT_PRIORITY
              percent:
                title: Percent
                maxLength: 3
                type: number
                description: "This field identifies the percentage of the charge associated with the detail category code that the third party Exemption will cover."
                x-lineageReferenceObject: TBRECAT_PERCENT
              minAmount:
                title: Minimum Amount
                type: number
                description: "This field indicates the minimum amount the student must pay for the charge associated with the detail category code, that the third party will not cover."
                x-lineageReferenceObject: TBRECAT_MIN_AMOUNT
              maxAmount:
                title: Maximum Amount
                type: number
                description: "This field indicates the maximum amount the third party Exemption will cover of the detail category code."
                x-lineageReferenceObject: TBRECAT_MAX_AMOUNT
              iESourceInd:
                title: Include Exclude Indicator
                type: string
                description: "Indicator telling whether the source codes in TBRECSI should be included or excluded. Value of Null indicates that all sources in TTVSRCE are included."
                x-lineageReferenceObject: TBRECAT_I_E_SOURCE_IND
            x-lineageReferenceObject: tbrccat
        tbrecsi:
          type: array
          items:
            required:
            - sourceCode
            type: object
            properties:
              sourceCode:
                title: Source
                maxLength: 30
                type: string
                description: "This field contains the source code which will be paid by the Exemption."
                x-lineageReferenceObject: TBRECSI_SOURCE_CODE
            x-lineageReferenceObject: tbrecsi
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
