openapi: 3.0.0
info:
  title: contract-payment-detail
  description: API for TSACPDT administrative page
  version: 1.0.0
  x-audience: all
  x-release-status: ga
  x-source-name: TSACPDT
  x-source-domain: Student
  x-source-title: Contract Payment Detail
  x-source-system: banner
  x-api-type: bus-poc
servers:
  - url: https://integrate.elluciancloud.com
    description: Ethos Integration API U.S.
  - url: https://integrate.elluciancloud.ca
    description: Ethos Integration API Canada
  - url: https://integrate.elluciancloud.ie
    description: Ethos Integration API Europe
  - url: https://integrate.elluciancloud.com.au
    description: Ethos Integration API Asia-Pacific
  - url: "{server_url}"
    description: Custom server url
    variables:
      server_url:
        default: localhost
paths:
  /api/contract-payment-detail:
    get:
      tags:
        - contract-payment-detail
      summary: Return resources from TSACPDT
      parameters:
        - name: X-SDE-Expand
          in: header
          description: The comma seperated value list of block names
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of resources requesting for this result set.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The 0 based index for a collection of resources for the page
            requested.
          required: false
          schema:
            type: integer
        - name: criteria
          in: query
          description: The filter criteria as a single URL query parameter. Use this
            parameter or the individual parameters listed. Must be a JSON
            representation of the property searching for. This can be any of the
            properties listed on the URL or QAPI and must be a json
            representation that can be validated against the GET schema. Limit
            and Offset are the only supported additional parameters on the URL.
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: string
        - name: contTranNumber
          in: query
          required: false
          schema:
            type: string
        - name: stuId
          in: query
          description: Student ID
          required: false
          schema:
            type: string
        - name: stuName
          in: query
          description: Name
          required: false
          schema:
            type: string
        - name: amount
          in: query
          description: Amount
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        - name: balance
          in: query
          description: Balance
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_BALANCE
        - name: contractNumber
          in: query
          description: Contract Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        - name: tranNumber
          in: query
          description: Transaction Number
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        - name: finalInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
        - name: refundInd
          in: query
          required: false
          schema:
            type: string
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        - name: summaryAmount
          in: query
          description: Total
          required: false
          schema:
            type: string
        - name: summaryBalance
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-payment-detail-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /api/contract-payment-detail/put:
    put:
      tags:
        - contract-payment-detail
      summary: Return resources from TSACPDT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/contract-payment-detail-1.0.0_put_request"
            example:
              id: A00010418
              contTranNumber: 1
              criteria.tranNumber: 2
              refundInd: Y
              finalInd: N
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-payment-detail-1.0.0_put_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
  /api/contract-payment-detail/post:
    post:
      tags:
        - contract-payment-detail
      summary: Return resources from TSACPDT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/contract-payment-detail-1.0.0_post_request"
            example:
              id: A00010418
              contTranNumber: 1
              TBRCPDT:
                - StuId: A40503974
                  amount: 1000
                - StuId: A40503974
                  amount: 1000
                  refundInd: Y
                - StuId: A00040460
                  amount: 1000
                  refundInd: Y
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-payment-detail-1.0.0_post_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []

  /qapi/contract-payment-detail:
    post:
      tags:
        - contract-payment-detail QAPI (Query by POST)
      summary: Return resources from TSACPDT
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              $ref: "#/components/schemas/contract-payment-detail-1.0.0_get_request"
            example:
              id: V9
              contTranNumber: 13
      responses:
        "200":
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response body is
                associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/contract-payment-detail-1.0.0_get_response"
        "400":
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/errors-2.0.0"
        "401":
          description: Failure. Unauthorized
      security:
        - BasicAuth: []
          EllucianOAuthUserToken: []
          EthosIntegrationBearer: []
components:
  schemas:
    contract-payment-detail-1.0.0_get_request:
      required:
        - amount
      type: object
      properties:
        amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        stuId:
          title: Student ID
          maxLength: 9
          type: string
        balance:
          title: Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRCPDT_BALANCE"
          x-lineageReferenceObject: TBRCPDT_BALANCE
        summaryBalance:
          maxLength: 22
          type: number
        refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_TRAN_NUMBER"
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        summaryAmount:
          title: Total
          maxLength: 22
          type: number
        id:
          title: Contract ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        stuName:
          title: Name
          maxLength: 230
          type: string
        contTranNumber:
          title: Trans Number
          maxLength: 8
          type: number
          description: "Lineage reference object : contTranNumber"
          x-lineageReferenceObject: contTranNumber
        finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
      x-lineageReferenceObject: TBRCPDT
    contract-payment-detail-1.0.0_get_response:
      required:
        - amount
      type: object
      properties:
        amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        stuId:
          title: Student ID
          maxLength: 9
          type: string
        balance:
          title: Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRCPDT_BALANCE"
          x-lineageReferenceObject: TBRCPDT_BALANCE
        summaryBalance:
          maxLength: 22
          type: number
        refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        summaryAmount:
          title: Total
          maxLength: 22
          type: number
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_TRAN_NUMBER"
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        stuName:
          title: Name
          maxLength: 230
          type: string
        finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
      x-lineageReferenceObject: tbrcpdt
    errors-2.0.0:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    contract-payment-detail-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        contTranNumber:
          type: string
        stuId:
          title: Student ID
          maxLength: 9
          type: string
        stuName:
          title: Name
          maxLength: 230
          type: string
        amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        balance:
          title: Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRCPDT_BALANCE"
          x-lineageReferenceObject: TBRCPDT_BALANCE
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_TRAN_NUMBER"
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
        refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        summaryAmount:
          title: Total
          maxLength: 22
          type: number
        summaryBalance:
          maxLength: 22
          type: number
    contract-payment-detail-1.0.0_post_request:
      required:
        - id
        - contTranNumber
        - TBRCPDT
      type: object
      properties:
        id:
          title: Contract ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        contTranNumber:
          title: Trans Number
          maxLength: 8
          type: number
          description: "Trans Number from TSACPDT key block"
          x-lineageReferenceObject: contTranNumber
        TBRCPDT:
          type: array
          items:
            type: object
            required:
              - StuId
              - amount
            properties:
              StuId:
                title: Student ID
                maxLength: 9
                type: string
              amount:
                title: Amount
                maxLength: 19
                type: number
                description: "Lineage reference object : TBRCPDT_AMOUNT"
                x-lineageReferenceObject: TBRCPDT_AMOUNT
              refundInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCPDT_REFUND_IND"
                x-lineageReferenceObject: TBRCPDT_REFUND_IND
              finalInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCPDT_FINAL_IND"
                x-lineageReferenceObject: TBRCPDT_FINAL_IND
              contractNumber:
                title: Contract Number
                maxLength: 8
                type: number
                description: "Contract Number associated with contract ID from TSACONT"
                x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
            x-lineageReferenceObject: tbrcpdt
    contract-payment-detail-1.0.0_post_response:
      type: object
      required:
        - stuId
        - amount
        - balance
        - tranNumber
        - summaryAmount
        - summaryBalance
        - finalInd
        - refundInd
      properties:
        stuId:
          title: Student ID
          maxLength: 9
          type: string
        stuName:
          title: Name
          maxLength: 230
          type: string
        summaryAmount:
          title: Total Amount
          maxLength: 22
          type: number
        summaryBalance:
          title: Total Balance
          maxLength: 22
          type: number
        amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        balance:
          title: Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRCPDT_BALANCE"
          x-lineageReferenceObject: TBRCPDT_BALANCE
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Contract Number associated with contract ID from TSACONT"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
        refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_TRAN_NUMBER"
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER

    contract-payment-detail-1.0.0_put_request:
      required:
        - id
        - contTranNumber
        - criteria.tranNumber
      type: object
      properties:
        id:
          title: Contract ID
          maxLength: 9
          type: string
          description: "Lineage reference object : id"
          x-lineageReferenceObject: id
        contTranNumber:
          title: Trans Number
          maxLength: 8
          type: number
          description: "Trans Number from TSACPDT key block"
          x-lineageReferenceObject: contTranNumber
        criteria.tranNumber:
          title: Transaction Number
          maxLength: 8
          type: number
          description: "Transaction Number from TSACPDT transaction Number column"
          x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        criteria.stuId:
          title: Student ID
          maxLength: 9
          type: string
        criteria.stuName:
          title: Name
          maxLength: 230
          type: string
        criteria.amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        criteria.balance:
          title: Balance
          maxLength: 17
          type: number
          description: "Lineage reference object : TBRCPDT_BALANCE"
          x-lineageReferenceObject: TBRCPDT_BALANCE
        criteria.contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Lineage reference object : TBRCPDT_CONTRACT_NUMBER"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        criteria.finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
        criteria.refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND
        amount:
          title: Amount
          maxLength: 19
          type: number
          description: "Lineage reference object : TBRCPDT_AMOUNT"
          x-lineageReferenceObject: TBRCPDT_AMOUNT
        contractNumber:
          title: Contract Number
          maxLength: 8
          type: number
          description: "Contract Number associated with contract ID from TSACONT"
          x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
        finalInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_FINAL_IND"
          x-lineageReferenceObject: TBRCPDT_FINAL_IND
        refundInd:
          maxLength: 1
          type: string
          description: "Lineage reference object : TBRCPDT_REFUND_IND"
          x-lineageReferenceObject: TBRCPDT_REFUND_IND

    contract-payment-detail-1.0.0_put_response:
      type: object
      properties:
        TBRCPDT:
          type: array
          items:
            type: object
            required:
              - stuId
              - amount
              - balance
              - tranNumber
              - summaryAmount
              - summaryBalance
              - finalInd
              - refundInd
            properties:
              stuId:
                title: Student ID
                maxLength: 9
                type: string
              stuName:
                title: Name
                maxLength: 230
              summaryAmount:
                title: Total Amount
                maxLength: 22
              summaryBalance:
                title: Total Balance
                maxLength: 22
                type: number
              amount:
                title: Amount
                maxLength: 19
                type: number
                description: "Lineage reference object : TBRCPDT_AMOUNT"
                x-lineageReferenceObject: TBRCPDT_AMOUNT
              balance:
                title: Balance
                maxLength: 17
                type: number
                description: "Lineage reference object : TBRCPDT_BALANCE"
                x-lineageReferenceObject: TBRCPDT_BALANCE
              contractNumber:
                title: Contract Number
                maxLength: 8
                type: number
                description: "Contract Number associated with contract ID from TSACONT"
                x-lineageReferenceObject: TBRCPDT_CONTRACT_NUMBER
              finalInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCPDT_FINAL_IND"
                x-lineageReferenceObject: TBRCPDT_FINAL_IND
              refundInd:
                maxLength: 1
                type: string
                description: "Lineage reference object : TBRCPDT_REFUND_IND"
                x-lineageReferenceObject: TBRCPDT_REFUND_IND
              tranNumber:
                title: Transaction Number
                maxLength: 8
                type: number
                description: "Lineage reference object : TBRCPDT_TRAN_NUMBER"
                x-lineageReferenceObject: TBRCPDT_TRAN_NUMBER
        TBRCPDT_CTL_BLOCK:
          type: array
          items:
            type: object
            required:
              - totalCharnges
              - totalPayments
              - variance
            properties:
              totalCharnges:
                title: Total Charges
                maxLength: 22
                type: number
              totalPayments:
                title: Total Payments
                maxLength: 22
                type: number
              variance:
                title: Variance
                maxLength: 22
                type: number

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    EllucianOAuthUserToken:
      type: http
      scheme: bearer
    EthosIntegrationBearer:
      type: http
      scheme: bearer
